// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ClinicCreds is the predicate function for cliniccreds builders.
type ClinicCreds func(*sql.Selector)

// Clinics is the predicate function for clinics builders.
type Clinics func(*sql.Selector)

// Doctors is the predicate function for doctors builders.
type Doctors func(*sql.Selector)

// Permissions is the predicate function for permissions builders.
type Permissions func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
