// Code generated by ent, DO NOT EDIT.

package cliniccreds

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the cliniccreds type in the database.
	Label = "clinic_creds"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSystem holds the string denoting the system field in the database.
	FieldSystem = "system"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// EdgeClinics holds the string denoting the clinics edge name in mutations.
	EdgeClinics = "clinics"
	// Table holds the table name of the cliniccreds in the database.
	Table = "clinic_creds"
	// ClinicsTable is the table that holds the clinics relation/edge.
	ClinicsTable = "clinic_creds"
	// ClinicsInverseTable is the table name for the Clinics entity.
	// It exists in this package in order to avoid circular dependency with the "clinics" package.
	ClinicsInverseTable = "clinics"
	// ClinicsColumn is the table column denoting the clinics relation/edge.
	ClinicsColumn = "clinics_clinic_creds"
)

// Columns holds all SQL columns for cliniccreds fields.
var Columns = []string{
	FieldID,
	FieldSystem,
	FieldUsername,
	FieldPassword,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "clinic_creds"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"clinics_clinic_creds",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// SystemValidator is a validator for the "system" field. It is called by the builders before save.
	SystemValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
)

// OrderOption defines the ordering options for the ClinicCreds queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySystem orders the results by the system field.
func BySystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystem, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByClinicsField orders the results by clinics field.
func ByClinicsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClinicsStep(), sql.OrderByField(field, opts...))
	}
}
func newClinicsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClinicsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClinicsTable, ClinicsColumn),
	)
}
