// Code generated by ent, DO NOT EDIT.

package cliniccreds

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLTE(FieldID, id))
}

// System applies equality check predicate on the "system" field. It's identical to SystemEQ.
func System(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldSystem, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldPassword, v))
}

// SystemEQ applies the EQ predicate on the "system" field.
func SystemEQ(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldSystem, v))
}

// SystemNEQ applies the NEQ predicate on the "system" field.
func SystemNEQ(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNEQ(FieldSystem, v))
}

// SystemIn applies the In predicate on the "system" field.
func SystemIn(vs ...string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldIn(FieldSystem, vs...))
}

// SystemNotIn applies the NotIn predicate on the "system" field.
func SystemNotIn(vs ...string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNotIn(FieldSystem, vs...))
}

// SystemGT applies the GT predicate on the "system" field.
func SystemGT(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGT(FieldSystem, v))
}

// SystemGTE applies the GTE predicate on the "system" field.
func SystemGTE(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGTE(FieldSystem, v))
}

// SystemLT applies the LT predicate on the "system" field.
func SystemLT(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLT(FieldSystem, v))
}

// SystemLTE applies the LTE predicate on the "system" field.
func SystemLTE(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLTE(FieldSystem, v))
}

// SystemContains applies the Contains predicate on the "system" field.
func SystemContains(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldContains(FieldSystem, v))
}

// SystemHasPrefix applies the HasPrefix predicate on the "system" field.
func SystemHasPrefix(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldHasPrefix(FieldSystem, v))
}

// SystemHasSuffix applies the HasSuffix predicate on the "system" field.
func SystemHasSuffix(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldHasSuffix(FieldSystem, v))
}

// SystemEqualFold applies the EqualFold predicate on the "system" field.
func SystemEqualFold(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEqualFold(FieldSystem, v))
}

// SystemContainsFold applies the ContainsFold predicate on the "system" field.
func SystemContainsFold(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldContainsFold(FieldSystem, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.FieldContainsFold(FieldPassword, v))
}

// HasClinics applies the HasEdge predicate on the "clinics" edge.
func HasClinics() predicate.ClinicCreds {
	return predicate.ClinicCreds(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClinicsTable, ClinicsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClinicsWith applies the HasEdge predicate on the "clinics" edge with a given conditions (other predicates).
func HasClinicsWith(preds ...predicate.Clinics) predicate.ClinicCreds {
	return predicate.ClinicCreds(func(s *sql.Selector) {
		step := newClinicsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClinicCreds) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClinicCreds) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClinicCreds) predicate.ClinicCreds {
	return predicate.ClinicCreds(sql.NotPredicates(p))
}
