// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Chaitu35/claimeasy/backend/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
	"github.com/Chaitu35/claimeasy/backend/ent/permissions"
	"github.com/Chaitu35/claimeasy/backend/ent/refreshtoken"
	"github.com/Chaitu35/claimeasy/backend/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ClinicCreds is the client for interacting with the ClinicCreds builders.
	ClinicCreds *ClinicCredsClient
	// Clinics is the client for interacting with the Clinics builders.
	Clinics *ClinicsClient
	// Doctors is the client for interacting with the Doctors builders.
	Doctors *DoctorsClient
	// Permissions is the client for interacting with the Permissions builders.
	Permissions *PermissionsClient
	// RefreshToken is the client for interacting with the RefreshToken builders.
	RefreshToken *RefreshTokenClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ClinicCreds = NewClinicCredsClient(c.config)
	c.Clinics = NewClinicsClient(c.config)
	c.Doctors = NewDoctorsClient(c.config)
	c.Permissions = NewPermissionsClient(c.config)
	c.RefreshToken = NewRefreshTokenClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ClinicCreds:  NewClinicCredsClient(cfg),
		Clinics:      NewClinicsClient(cfg),
		Doctors:      NewDoctorsClient(cfg),
		Permissions:  NewPermissionsClient(cfg),
		RefreshToken: NewRefreshTokenClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		ClinicCreds:  NewClinicCredsClient(cfg),
		Clinics:      NewClinicsClient(cfg),
		Doctors:      NewDoctorsClient(cfg),
		Permissions:  NewPermissionsClient(cfg),
		RefreshToken: NewRefreshTokenClient(cfg),
		User:         NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ClinicCreds.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.ClinicCreds, c.Clinics, c.Doctors, c.Permissions, c.RefreshToken, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.ClinicCreds, c.Clinics, c.Doctors, c.Permissions, c.RefreshToken, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ClinicCredsMutation:
		return c.ClinicCreds.mutate(ctx, m)
	case *ClinicsMutation:
		return c.Clinics.mutate(ctx, m)
	case *DoctorsMutation:
		return c.Doctors.mutate(ctx, m)
	case *PermissionsMutation:
		return c.Permissions.mutate(ctx, m)
	case *RefreshTokenMutation:
		return c.RefreshToken.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ClinicCredsClient is a client for the ClinicCreds schema.
type ClinicCredsClient struct {
	config
}

// NewClinicCredsClient returns a client for the ClinicCreds from the given config.
func NewClinicCredsClient(c config) *ClinicCredsClient {
	return &ClinicCredsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cliniccreds.Hooks(f(g(h())))`.
func (c *ClinicCredsClient) Use(hooks ...Hook) {
	c.hooks.ClinicCreds = append(c.hooks.ClinicCreds, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cliniccreds.Intercept(f(g(h())))`.
func (c *ClinicCredsClient) Intercept(interceptors ...Interceptor) {
	c.inters.ClinicCreds = append(c.inters.ClinicCreds, interceptors...)
}

// Create returns a builder for creating a ClinicCreds entity.
func (c *ClinicCredsClient) Create() *ClinicCredsCreate {
	mutation := newClinicCredsMutation(c.config, OpCreate)
	return &ClinicCredsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ClinicCreds entities.
func (c *ClinicCredsClient) CreateBulk(builders ...*ClinicCredsCreate) *ClinicCredsCreateBulk {
	return &ClinicCredsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ClinicCredsClient) MapCreateBulk(slice any, setFunc func(*ClinicCredsCreate, int)) *ClinicCredsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ClinicCredsCreateBulk{err: fmt.Errorf("calling to ClinicCredsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ClinicCredsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ClinicCredsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ClinicCreds.
func (c *ClinicCredsClient) Update() *ClinicCredsUpdate {
	mutation := newClinicCredsMutation(c.config, OpUpdate)
	return &ClinicCredsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ClinicCredsClient) UpdateOne(cc *ClinicCreds) *ClinicCredsUpdateOne {
	mutation := newClinicCredsMutation(c.config, OpUpdateOne, withClinicCreds(cc))
	return &ClinicCredsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ClinicCredsClient) UpdateOneID(id int) *ClinicCredsUpdateOne {
	mutation := newClinicCredsMutation(c.config, OpUpdateOne, withClinicCredsID(id))
	return &ClinicCredsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ClinicCreds.
func (c *ClinicCredsClient) Delete() *ClinicCredsDelete {
	mutation := newClinicCredsMutation(c.config, OpDelete)
	return &ClinicCredsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ClinicCredsClient) DeleteOne(cc *ClinicCreds) *ClinicCredsDeleteOne {
	return c.DeleteOneID(cc.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ClinicCredsClient) DeleteOneID(id int) *ClinicCredsDeleteOne {
	builder := c.Delete().Where(cliniccreds.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ClinicCredsDeleteOne{builder}
}

// Query returns a query builder for ClinicCreds.
func (c *ClinicCredsClient) Query() *ClinicCredsQuery {
	return &ClinicCredsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeClinicCreds},
		inters: c.Interceptors(),
	}
}

// Get returns a ClinicCreds entity by its id.
func (c *ClinicCredsClient) Get(ctx context.Context, id int) (*ClinicCreds, error) {
	return c.Query().Where(cliniccreds.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ClinicCredsClient) GetX(ctx context.Context, id int) *ClinicCreds {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryClinics queries the clinics edge of a ClinicCreds.
func (c *ClinicCredsClient) QueryClinics(cc *ClinicCreds) *ClinicsQuery {
	query := (&ClinicsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cc.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(cliniccreds.Table, cliniccreds.FieldID, id),
			sqlgraph.To(clinics.Table, clinics.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cliniccreds.ClinicsTable, cliniccreds.ClinicsColumn),
		)
		fromV = sqlgraph.Neighbors(cc.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ClinicCredsClient) Hooks() []Hook {
	return c.hooks.ClinicCreds
}

// Interceptors returns the client interceptors.
func (c *ClinicCredsClient) Interceptors() []Interceptor {
	return c.inters.ClinicCreds
}

func (c *ClinicCredsClient) mutate(ctx context.Context, m *ClinicCredsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ClinicCredsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ClinicCredsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ClinicCredsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ClinicCredsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ClinicCreds mutation op: %q", m.Op())
	}
}

// ClinicsClient is a client for the Clinics schema.
type ClinicsClient struct {
	config
}

// NewClinicsClient returns a client for the Clinics from the given config.
func NewClinicsClient(c config) *ClinicsClient {
	return &ClinicsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `clinics.Hooks(f(g(h())))`.
func (c *ClinicsClient) Use(hooks ...Hook) {
	c.hooks.Clinics = append(c.hooks.Clinics, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `clinics.Intercept(f(g(h())))`.
func (c *ClinicsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Clinics = append(c.inters.Clinics, interceptors...)
}

// Create returns a builder for creating a Clinics entity.
func (c *ClinicsClient) Create() *ClinicsCreate {
	mutation := newClinicsMutation(c.config, OpCreate)
	return &ClinicsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Clinics entities.
func (c *ClinicsClient) CreateBulk(builders ...*ClinicsCreate) *ClinicsCreateBulk {
	return &ClinicsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ClinicsClient) MapCreateBulk(slice any, setFunc func(*ClinicsCreate, int)) *ClinicsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ClinicsCreateBulk{err: fmt.Errorf("calling to ClinicsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ClinicsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ClinicsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Clinics.
func (c *ClinicsClient) Update() *ClinicsUpdate {
	mutation := newClinicsMutation(c.config, OpUpdate)
	return &ClinicsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ClinicsClient) UpdateOne(cl *Clinics) *ClinicsUpdateOne {
	mutation := newClinicsMutation(c.config, OpUpdateOne, withClinics(cl))
	return &ClinicsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ClinicsClient) UpdateOneID(id int) *ClinicsUpdateOne {
	mutation := newClinicsMutation(c.config, OpUpdateOne, withClinicsID(id))
	return &ClinicsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Clinics.
func (c *ClinicsClient) Delete() *ClinicsDelete {
	mutation := newClinicsMutation(c.config, OpDelete)
	return &ClinicsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ClinicsClient) DeleteOne(cl *Clinics) *ClinicsDeleteOne {
	return c.DeleteOneID(cl.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ClinicsClient) DeleteOneID(id int) *ClinicsDeleteOne {
	builder := c.Delete().Where(clinics.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ClinicsDeleteOne{builder}
}

// Query returns a query builder for Clinics.
func (c *ClinicsClient) Query() *ClinicsQuery {
	return &ClinicsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeClinics},
		inters: c.Interceptors(),
	}
}

// Get returns a Clinics entity by its id.
func (c *ClinicsClient) Get(ctx context.Context, id int) (*Clinics, error) {
	return c.Query().Where(clinics.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ClinicsClient) GetX(ctx context.Context, id int) *Clinics {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryClinicCreds queries the clinic_creds edge of a Clinics.
func (c *ClinicsClient) QueryClinicCreds(cl *Clinics) *ClinicCredsQuery {
	query := (&ClinicCredsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(clinics.Table, clinics.FieldID, id),
			sqlgraph.To(cliniccreds.Table, cliniccreds.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, clinics.ClinicCredsTable, clinics.ClinicCredsColumn),
		)
		fromV = sqlgraph.Neighbors(cl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDoctors queries the doctors edge of a Clinics.
func (c *ClinicsClient) QueryDoctors(cl *Clinics) *DoctorsQuery {
	query := (&DoctorsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cl.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(clinics.Table, clinics.FieldID, id),
			sqlgraph.To(doctors.Table, doctors.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, clinics.DoctorsTable, clinics.DoctorsColumn),
		)
		fromV = sqlgraph.Neighbors(cl.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ClinicsClient) Hooks() []Hook {
	return c.hooks.Clinics
}

// Interceptors returns the client interceptors.
func (c *ClinicsClient) Interceptors() []Interceptor {
	return c.inters.Clinics
}

func (c *ClinicsClient) mutate(ctx context.Context, m *ClinicsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ClinicsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ClinicsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ClinicsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ClinicsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Clinics mutation op: %q", m.Op())
	}
}

// DoctorsClient is a client for the Doctors schema.
type DoctorsClient struct {
	config
}

// NewDoctorsClient returns a client for the Doctors from the given config.
func NewDoctorsClient(c config) *DoctorsClient {
	return &DoctorsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `doctors.Hooks(f(g(h())))`.
func (c *DoctorsClient) Use(hooks ...Hook) {
	c.hooks.Doctors = append(c.hooks.Doctors, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `doctors.Intercept(f(g(h())))`.
func (c *DoctorsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Doctors = append(c.inters.Doctors, interceptors...)
}

// Create returns a builder for creating a Doctors entity.
func (c *DoctorsClient) Create() *DoctorsCreate {
	mutation := newDoctorsMutation(c.config, OpCreate)
	return &DoctorsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Doctors entities.
func (c *DoctorsClient) CreateBulk(builders ...*DoctorsCreate) *DoctorsCreateBulk {
	return &DoctorsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DoctorsClient) MapCreateBulk(slice any, setFunc func(*DoctorsCreate, int)) *DoctorsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DoctorsCreateBulk{err: fmt.Errorf("calling to DoctorsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DoctorsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DoctorsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Doctors.
func (c *DoctorsClient) Update() *DoctorsUpdate {
	mutation := newDoctorsMutation(c.config, OpUpdate)
	return &DoctorsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DoctorsClient) UpdateOne(d *Doctors) *DoctorsUpdateOne {
	mutation := newDoctorsMutation(c.config, OpUpdateOne, withDoctors(d))
	return &DoctorsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DoctorsClient) UpdateOneID(id int) *DoctorsUpdateOne {
	mutation := newDoctorsMutation(c.config, OpUpdateOne, withDoctorsID(id))
	return &DoctorsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Doctors.
func (c *DoctorsClient) Delete() *DoctorsDelete {
	mutation := newDoctorsMutation(c.config, OpDelete)
	return &DoctorsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DoctorsClient) DeleteOne(d *Doctors) *DoctorsDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DoctorsClient) DeleteOneID(id int) *DoctorsDeleteOne {
	builder := c.Delete().Where(doctors.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DoctorsDeleteOne{builder}
}

// Query returns a query builder for Doctors.
func (c *DoctorsClient) Query() *DoctorsQuery {
	return &DoctorsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDoctors},
		inters: c.Interceptors(),
	}
}

// Get returns a Doctors entity by its id.
func (c *DoctorsClient) Get(ctx context.Context, id int) (*Doctors, error) {
	return c.Query().Where(doctors.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DoctorsClient) GetX(ctx context.Context, id int) *Doctors {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryClinics queries the clinics edge of a Doctors.
func (c *DoctorsClient) QueryClinics(d *Doctors) *ClinicsQuery {
	query := (&ClinicsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(doctors.Table, doctors.FieldID, id),
			sqlgraph.To(clinics.Table, clinics.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, doctors.ClinicsTable, doctors.ClinicsColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DoctorsClient) Hooks() []Hook {
	return c.hooks.Doctors
}

// Interceptors returns the client interceptors.
func (c *DoctorsClient) Interceptors() []Interceptor {
	return c.inters.Doctors
}

func (c *DoctorsClient) mutate(ctx context.Context, m *DoctorsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DoctorsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DoctorsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DoctorsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DoctorsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Doctors mutation op: %q", m.Op())
	}
}

// PermissionsClient is a client for the Permissions schema.
type PermissionsClient struct {
	config
}

// NewPermissionsClient returns a client for the Permissions from the given config.
func NewPermissionsClient(c config) *PermissionsClient {
	return &PermissionsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `permissions.Hooks(f(g(h())))`.
func (c *PermissionsClient) Use(hooks ...Hook) {
	c.hooks.Permissions = append(c.hooks.Permissions, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `permissions.Intercept(f(g(h())))`.
func (c *PermissionsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Permissions = append(c.inters.Permissions, interceptors...)
}

// Create returns a builder for creating a Permissions entity.
func (c *PermissionsClient) Create() *PermissionsCreate {
	mutation := newPermissionsMutation(c.config, OpCreate)
	return &PermissionsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Permissions entities.
func (c *PermissionsClient) CreateBulk(builders ...*PermissionsCreate) *PermissionsCreateBulk {
	return &PermissionsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PermissionsClient) MapCreateBulk(slice any, setFunc func(*PermissionsCreate, int)) *PermissionsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PermissionsCreateBulk{err: fmt.Errorf("calling to PermissionsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PermissionsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PermissionsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Permissions.
func (c *PermissionsClient) Update() *PermissionsUpdate {
	mutation := newPermissionsMutation(c.config, OpUpdate)
	return &PermissionsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PermissionsClient) UpdateOne(pe *Permissions) *PermissionsUpdateOne {
	mutation := newPermissionsMutation(c.config, OpUpdateOne, withPermissions(pe))
	return &PermissionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PermissionsClient) UpdateOneID(id int) *PermissionsUpdateOne {
	mutation := newPermissionsMutation(c.config, OpUpdateOne, withPermissionsID(id))
	return &PermissionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Permissions.
func (c *PermissionsClient) Delete() *PermissionsDelete {
	mutation := newPermissionsMutation(c.config, OpDelete)
	return &PermissionsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PermissionsClient) DeleteOne(pe *Permissions) *PermissionsDeleteOne {
	return c.DeleteOneID(pe.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PermissionsClient) DeleteOneID(id int) *PermissionsDeleteOne {
	builder := c.Delete().Where(permissions.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PermissionsDeleteOne{builder}
}

// Query returns a query builder for Permissions.
func (c *PermissionsClient) Query() *PermissionsQuery {
	return &PermissionsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePermissions},
		inters: c.Interceptors(),
	}
}

// Get returns a Permissions entity by its id.
func (c *PermissionsClient) Get(ctx context.Context, id int) (*Permissions, error) {
	return c.Query().Where(permissions.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PermissionsClient) GetX(ctx context.Context, id int) *Permissions {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Permissions.
func (c *PermissionsClient) QueryUser(pe *Permissions) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := pe.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(permissions.Table, permissions.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, permissions.UserTable, permissions.UserColumn),
		)
		fromV = sqlgraph.Neighbors(pe.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PermissionsClient) Hooks() []Hook {
	return c.hooks.Permissions
}

// Interceptors returns the client interceptors.
func (c *PermissionsClient) Interceptors() []Interceptor {
	return c.inters.Permissions
}

func (c *PermissionsClient) mutate(ctx context.Context, m *PermissionsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PermissionsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PermissionsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PermissionsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PermissionsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Permissions mutation op: %q", m.Op())
	}
}

// RefreshTokenClient is a client for the RefreshToken schema.
type RefreshTokenClient struct {
	config
}

// NewRefreshTokenClient returns a client for the RefreshToken from the given config.
func NewRefreshTokenClient(c config) *RefreshTokenClient {
	return &RefreshTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refreshtoken.Hooks(f(g(h())))`.
func (c *RefreshTokenClient) Use(hooks ...Hook) {
	c.hooks.RefreshToken = append(c.hooks.RefreshToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refreshtoken.Intercept(f(g(h())))`.
func (c *RefreshTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefreshToken = append(c.inters.RefreshToken, interceptors...)
}

// Create returns a builder for creating a RefreshToken entity.
func (c *RefreshTokenClient) Create() *RefreshTokenCreate {
	mutation := newRefreshTokenMutation(c.config, OpCreate)
	return &RefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefreshToken entities.
func (c *RefreshTokenClient) CreateBulk(builders ...*RefreshTokenCreate) *RefreshTokenCreateBulk {
	return &RefreshTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefreshTokenClient) MapCreateBulk(slice any, setFunc func(*RefreshTokenCreate, int)) *RefreshTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefreshTokenCreateBulk{err: fmt.Errorf("calling to RefreshTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefreshTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefreshTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefreshToken.
func (c *RefreshTokenClient) Update() *RefreshTokenUpdate {
	mutation := newRefreshTokenMutation(c.config, OpUpdate)
	return &RefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefreshTokenClient) UpdateOne(rt *RefreshToken) *RefreshTokenUpdateOne {
	mutation := newRefreshTokenMutation(c.config, OpUpdateOne, withRefreshToken(rt))
	return &RefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefreshTokenClient) UpdateOneID(id int) *RefreshTokenUpdateOne {
	mutation := newRefreshTokenMutation(c.config, OpUpdateOne, withRefreshTokenID(id))
	return &RefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefreshToken.
func (c *RefreshTokenClient) Delete() *RefreshTokenDelete {
	mutation := newRefreshTokenMutation(c.config, OpDelete)
	return &RefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefreshTokenClient) DeleteOne(rt *RefreshToken) *RefreshTokenDeleteOne {
	return c.DeleteOneID(rt.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefreshTokenClient) DeleteOneID(id int) *RefreshTokenDeleteOne {
	builder := c.Delete().Where(refreshtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefreshTokenDeleteOne{builder}
}

// Query returns a query builder for RefreshToken.
func (c *RefreshTokenClient) Query() *RefreshTokenQuery {
	return &RefreshTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefreshToken},
		inters: c.Interceptors(),
	}
}

// Get returns a RefreshToken entity by its id.
func (c *RefreshTokenClient) Get(ctx context.Context, id int) (*RefreshToken, error) {
	return c.Query().Where(refreshtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RefreshTokenClient) GetX(ctx context.Context, id int) *RefreshToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RefreshTokenClient) Hooks() []Hook {
	return c.hooks.RefreshToken
}

// Interceptors returns the client interceptors.
func (c *RefreshTokenClient) Interceptors() []Interceptor {
	return c.inters.RefreshToken
}

func (c *RefreshTokenClient) mutate(ctx context.Context, m *RefreshTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefreshTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefreshTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefreshTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefreshTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefreshToken mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryPermissions queries the permissions edge of a User.
func (c *UserClient) QueryPermissions(u *User) *PermissionsQuery {
	query := (&PermissionsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(permissions.Table, permissions.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.PermissionsTable, user.PermissionsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ClinicCreds, Clinics, Doctors, Permissions, RefreshToken, User []ent.Hook
	}
	inters struct {
		ClinicCreds, Clinics, Doctors, Permissions, RefreshToken, User []ent.Interceptor
	}
)
