// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// ClinicCredsUpdate is the builder for updating ClinicCreds entities.
type ClinicCredsUpdate struct {
	config
	hooks    []Hook
	mutation *ClinicCredsMutation
}

// Where appends a list predicates to the ClinicCredsUpdate builder.
func (ccu *ClinicCredsUpdate) Where(ps ...predicate.ClinicCreds) *ClinicCredsUpdate {
	ccu.mutation.Where(ps...)
	return ccu
}

// SetSystem sets the "system" field.
func (ccu *ClinicCredsUpdate) SetSystem(s string) *ClinicCredsUpdate {
	ccu.mutation.SetSystem(s)
	return ccu
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (ccu *ClinicCredsUpdate) SetNillableSystem(s *string) *ClinicCredsUpdate {
	if s != nil {
		ccu.SetSystem(*s)
	}
	return ccu
}

// SetUsername sets the "username" field.
func (ccu *ClinicCredsUpdate) SetUsername(s string) *ClinicCredsUpdate {
	ccu.mutation.SetUsername(s)
	return ccu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (ccu *ClinicCredsUpdate) SetNillableUsername(s *string) *ClinicCredsUpdate {
	if s != nil {
		ccu.SetUsername(*s)
	}
	return ccu
}

// SetPassword sets the "password" field.
func (ccu *ClinicCredsUpdate) SetPassword(s string) *ClinicCredsUpdate {
	ccu.mutation.SetPassword(s)
	return ccu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (ccu *ClinicCredsUpdate) SetNillablePassword(s *string) *ClinicCredsUpdate {
	if s != nil {
		ccu.SetPassword(*s)
	}
	return ccu
}

// SetClinicsID sets the "clinics" edge to the Clinics entity by ID.
func (ccu *ClinicCredsUpdate) SetClinicsID(id int) *ClinicCredsUpdate {
	ccu.mutation.SetClinicsID(id)
	return ccu
}

// SetClinics sets the "clinics" edge to the Clinics entity.
func (ccu *ClinicCredsUpdate) SetClinics(c *Clinics) *ClinicCredsUpdate {
	return ccu.SetClinicsID(c.ID)
}

// Mutation returns the ClinicCredsMutation object of the builder.
func (ccu *ClinicCredsUpdate) Mutation() *ClinicCredsMutation {
	return ccu.mutation
}

// ClearClinics clears the "clinics" edge to the Clinics entity.
func (ccu *ClinicCredsUpdate) ClearClinics() *ClinicCredsUpdate {
	ccu.mutation.ClearClinics()
	return ccu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ccu *ClinicCredsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ccu.sqlSave, ccu.mutation, ccu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ccu *ClinicCredsUpdate) SaveX(ctx context.Context) int {
	affected, err := ccu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ccu *ClinicCredsUpdate) Exec(ctx context.Context) error {
	_, err := ccu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccu *ClinicCredsUpdate) ExecX(ctx context.Context) {
	if err := ccu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ccu *ClinicCredsUpdate) check() error {
	if v, ok := ccu.mutation.System(); ok {
		if err := cliniccreds.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.system": %w`, err)}
		}
	}
	if v, ok := ccu.mutation.Username(); ok {
		if err := cliniccreds.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.username": %w`, err)}
		}
	}
	if v, ok := ccu.mutation.Password(); ok {
		if err := cliniccreds.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.password": %w`, err)}
		}
	}
	if ccu.mutation.ClinicsCleared() && len(ccu.mutation.ClinicsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClinicCreds.clinics"`)
	}
	return nil
}

func (ccu *ClinicCredsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ccu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(cliniccreds.Table, cliniccreds.Columns, sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt))
	if ps := ccu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ccu.mutation.System(); ok {
		_spec.SetField(cliniccreds.FieldSystem, field.TypeString, value)
	}
	if value, ok := ccu.mutation.Username(); ok {
		_spec.SetField(cliniccreds.FieldUsername, field.TypeString, value)
	}
	if value, ok := ccu.mutation.Password(); ok {
		_spec.SetField(cliniccreds.FieldPassword, field.TypeString, value)
	}
	if ccu.mutation.ClinicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cliniccreds.ClinicsTable,
			Columns: []string{cliniccreds.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ccu.mutation.ClinicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cliniccreds.ClinicsTable,
			Columns: []string{cliniccreds.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ccu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cliniccreds.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ccu.mutation.done = true
	return n, nil
}

// ClinicCredsUpdateOne is the builder for updating a single ClinicCreds entity.
type ClinicCredsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClinicCredsMutation
}

// SetSystem sets the "system" field.
func (ccuo *ClinicCredsUpdateOne) SetSystem(s string) *ClinicCredsUpdateOne {
	ccuo.mutation.SetSystem(s)
	return ccuo
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (ccuo *ClinicCredsUpdateOne) SetNillableSystem(s *string) *ClinicCredsUpdateOne {
	if s != nil {
		ccuo.SetSystem(*s)
	}
	return ccuo
}

// SetUsername sets the "username" field.
func (ccuo *ClinicCredsUpdateOne) SetUsername(s string) *ClinicCredsUpdateOne {
	ccuo.mutation.SetUsername(s)
	return ccuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (ccuo *ClinicCredsUpdateOne) SetNillableUsername(s *string) *ClinicCredsUpdateOne {
	if s != nil {
		ccuo.SetUsername(*s)
	}
	return ccuo
}

// SetPassword sets the "password" field.
func (ccuo *ClinicCredsUpdateOne) SetPassword(s string) *ClinicCredsUpdateOne {
	ccuo.mutation.SetPassword(s)
	return ccuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (ccuo *ClinicCredsUpdateOne) SetNillablePassword(s *string) *ClinicCredsUpdateOne {
	if s != nil {
		ccuo.SetPassword(*s)
	}
	return ccuo
}

// SetClinicsID sets the "clinics" edge to the Clinics entity by ID.
func (ccuo *ClinicCredsUpdateOne) SetClinicsID(id int) *ClinicCredsUpdateOne {
	ccuo.mutation.SetClinicsID(id)
	return ccuo
}

// SetClinics sets the "clinics" edge to the Clinics entity.
func (ccuo *ClinicCredsUpdateOne) SetClinics(c *Clinics) *ClinicCredsUpdateOne {
	return ccuo.SetClinicsID(c.ID)
}

// Mutation returns the ClinicCredsMutation object of the builder.
func (ccuo *ClinicCredsUpdateOne) Mutation() *ClinicCredsMutation {
	return ccuo.mutation
}

// ClearClinics clears the "clinics" edge to the Clinics entity.
func (ccuo *ClinicCredsUpdateOne) ClearClinics() *ClinicCredsUpdateOne {
	ccuo.mutation.ClearClinics()
	return ccuo
}

// Where appends a list predicates to the ClinicCredsUpdate builder.
func (ccuo *ClinicCredsUpdateOne) Where(ps ...predicate.ClinicCreds) *ClinicCredsUpdateOne {
	ccuo.mutation.Where(ps...)
	return ccuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ccuo *ClinicCredsUpdateOne) Select(field string, fields ...string) *ClinicCredsUpdateOne {
	ccuo.fields = append([]string{field}, fields...)
	return ccuo
}

// Save executes the query and returns the updated ClinicCreds entity.
func (ccuo *ClinicCredsUpdateOne) Save(ctx context.Context) (*ClinicCreds, error) {
	return withHooks(ctx, ccuo.sqlSave, ccuo.mutation, ccuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ccuo *ClinicCredsUpdateOne) SaveX(ctx context.Context) *ClinicCreds {
	node, err := ccuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ccuo *ClinicCredsUpdateOne) Exec(ctx context.Context) error {
	_, err := ccuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccuo *ClinicCredsUpdateOne) ExecX(ctx context.Context) {
	if err := ccuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ccuo *ClinicCredsUpdateOne) check() error {
	if v, ok := ccuo.mutation.System(); ok {
		if err := cliniccreds.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.system": %w`, err)}
		}
	}
	if v, ok := ccuo.mutation.Username(); ok {
		if err := cliniccreds.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.username": %w`, err)}
		}
	}
	if v, ok := ccuo.mutation.Password(); ok {
		if err := cliniccreds.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.password": %w`, err)}
		}
	}
	if ccuo.mutation.ClinicsCleared() && len(ccuo.mutation.ClinicsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClinicCreds.clinics"`)
	}
	return nil
}

func (ccuo *ClinicCredsUpdateOne) sqlSave(ctx context.Context) (_node *ClinicCreds, err error) {
	if err := ccuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cliniccreds.Table, cliniccreds.Columns, sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt))
	id, ok := ccuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClinicCreds.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ccuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cliniccreds.FieldID)
		for _, f := range fields {
			if !cliniccreds.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cliniccreds.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ccuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ccuo.mutation.System(); ok {
		_spec.SetField(cliniccreds.FieldSystem, field.TypeString, value)
	}
	if value, ok := ccuo.mutation.Username(); ok {
		_spec.SetField(cliniccreds.FieldUsername, field.TypeString, value)
	}
	if value, ok := ccuo.mutation.Password(); ok {
		_spec.SetField(cliniccreds.FieldPassword, field.TypeString, value)
	}
	if ccuo.mutation.ClinicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cliniccreds.ClinicsTable,
			Columns: []string{cliniccreds.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ccuo.mutation.ClinicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cliniccreds.ClinicsTable,
			Columns: []string{cliniccreds.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClinicCreds{config: ccuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ccuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cliniccreds.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ccuo.mutation.done = true
	return _node, nil
}
