// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// ClinicCredsDelete is the builder for deleting a ClinicCreds entity.
type ClinicCredsDelete struct {
	config
	hooks    []Hook
	mutation *ClinicCredsMutation
}

// Where appends a list predicates to the ClinicCredsDelete builder.
func (ccd *ClinicCredsDelete) Where(ps ...predicate.ClinicCreds) *ClinicCredsDelete {
	ccd.mutation.Where(ps...)
	return ccd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ccd *ClinicCredsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ccd.sqlExec, ccd.mutation, ccd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ccd *ClinicCredsDelete) ExecX(ctx context.Context) int {
	n, err := ccd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ccd *ClinicCredsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cliniccreds.Table, sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt))
	if ps := ccd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ccd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ccd.mutation.done = true
	return affected, err
}

// ClinicCredsDeleteOne is the builder for deleting a single ClinicCreds entity.
type ClinicCredsDeleteOne struct {
	ccd *ClinicCredsDelete
}

// Where appends a list predicates to the ClinicCredsDelete builder.
func (ccdo *ClinicCredsDeleteOne) Where(ps ...predicate.ClinicCreds) *ClinicCredsDeleteOne {
	ccdo.ccd.mutation.Where(ps...)
	return ccdo
}

// Exec executes the deletion query.
func (ccdo *ClinicCredsDeleteOne) Exec(ctx context.Context) error {
	n, err := ccdo.ccd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cliniccreds.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ccdo *ClinicCredsDeleteOne) ExecX(ctx context.Context) {
	if err := ccdo.Exec(ctx); err != nil {
		panic(err)
	}
}
