// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// ClinicsQuery is the builder for querying Clinics entities.
type ClinicsQuery struct {
	config
	ctx             *QueryContext
	order           []clinics.OrderOption
	inters          []Interceptor
	predicates      []predicate.Clinics
	withClinicCreds *ClinicCredsQuery
	withDoctors     *DoctorsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClinicsQuery builder.
func (cq *ClinicsQuery) Where(ps ...predicate.Clinics) *ClinicsQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ClinicsQuery) Limit(limit int) *ClinicsQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ClinicsQuery) Offset(offset int) *ClinicsQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ClinicsQuery) Unique(unique bool) *ClinicsQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ClinicsQuery) Order(o ...clinics.OrderOption) *ClinicsQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryClinicCreds chains the current query on the "clinic_creds" edge.
func (cq *ClinicsQuery) QueryClinicCreds() *ClinicCredsQuery {
	query := (&ClinicCredsClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(clinics.Table, clinics.FieldID, selector),
			sqlgraph.To(cliniccreds.Table, cliniccreds.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, clinics.ClinicCredsTable, clinics.ClinicCredsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDoctors chains the current query on the "doctors" edge.
func (cq *ClinicsQuery) QueryDoctors() *DoctorsQuery {
	query := (&DoctorsClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(clinics.Table, clinics.FieldID, selector),
			sqlgraph.To(doctors.Table, doctors.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, clinics.DoctorsTable, clinics.DoctorsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Clinics entity from the query.
// Returns a *NotFoundError when no Clinics was found.
func (cq *ClinicsQuery) First(ctx context.Context) (*Clinics, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{clinics.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ClinicsQuery) FirstX(ctx context.Context) *Clinics {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Clinics ID from the query.
// Returns a *NotFoundError when no Clinics ID was found.
func (cq *ClinicsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{clinics.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ClinicsQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Clinics entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Clinics entity is found.
// Returns a *NotFoundError when no Clinics entities are found.
func (cq *ClinicsQuery) Only(ctx context.Context) (*Clinics, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{clinics.Label}
	default:
		return nil, &NotSingularError{clinics.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ClinicsQuery) OnlyX(ctx context.Context) *Clinics {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Clinics ID in the query.
// Returns a *NotSingularError when more than one Clinics ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ClinicsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{clinics.Label}
	default:
		err = &NotSingularError{clinics.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ClinicsQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ClinicsSlice.
func (cq *ClinicsQuery) All(ctx context.Context) ([]*Clinics, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Clinics, *ClinicsQuery]()
	return withInterceptors[[]*Clinics](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ClinicsQuery) AllX(ctx context.Context) []*Clinics {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Clinics IDs.
func (cq *ClinicsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(clinics.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ClinicsQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ClinicsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ClinicsQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ClinicsQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ClinicsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ClinicsQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClinicsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ClinicsQuery) Clone() *ClinicsQuery {
	if cq == nil {
		return nil
	}
	return &ClinicsQuery{
		config:          cq.config,
		ctx:             cq.ctx.Clone(),
		order:           append([]clinics.OrderOption{}, cq.order...),
		inters:          append([]Interceptor{}, cq.inters...),
		predicates:      append([]predicate.Clinics{}, cq.predicates...),
		withClinicCreds: cq.withClinicCreds.Clone(),
		withDoctors:     cq.withDoctors.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithClinicCreds tells the query-builder to eager-load the nodes that are connected to
// the "clinic_creds" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClinicsQuery) WithClinicCreds(opts ...func(*ClinicCredsQuery)) *ClinicsQuery {
	query := (&ClinicCredsClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withClinicCreds = query
	return cq
}

// WithDoctors tells the query-builder to eager-load the nodes that are connected to
// the "doctors" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClinicsQuery) WithDoctors(opts ...func(*DoctorsQuery)) *ClinicsQuery {
	query := (&DoctorsClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withDoctors = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Clinics.Query().
//		GroupBy(clinics.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ClinicsQuery) GroupBy(field string, fields ...string) *ClinicsGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClinicsGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = clinics.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Clinics.Query().
//		Select(clinics.FieldName).
//		Scan(ctx, &v)
func (cq *ClinicsQuery) Select(fields ...string) *ClinicsSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ClinicsSelect{ClinicsQuery: cq}
	sbuild.label = clinics.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClinicsSelect configured with the given aggregations.
func (cq *ClinicsQuery) Aggregate(fns ...AggregateFunc) *ClinicsSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ClinicsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !clinics.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ClinicsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Clinics, error) {
	var (
		nodes       = []*Clinics{}
		_spec       = cq.querySpec()
		loadedTypes = [2]bool{
			cq.withClinicCreds != nil,
			cq.withDoctors != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Clinics).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Clinics{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withClinicCreds; query != nil {
		if err := cq.loadClinicCreds(ctx, query, nodes,
			func(n *Clinics) { n.Edges.ClinicCreds = []*ClinicCreds{} },
			func(n *Clinics, e *ClinicCreds) { n.Edges.ClinicCreds = append(n.Edges.ClinicCreds, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withDoctors; query != nil {
		if err := cq.loadDoctors(ctx, query, nodes,
			func(n *Clinics) { n.Edges.Doctors = []*Doctors{} },
			func(n *Clinics, e *Doctors) { n.Edges.Doctors = append(n.Edges.Doctors, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ClinicsQuery) loadClinicCreds(ctx context.Context, query *ClinicCredsQuery, nodes []*Clinics, init func(*Clinics), assign func(*Clinics, *ClinicCreds)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Clinics)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ClinicCreds(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(clinics.ClinicCredsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.clinics_clinic_creds
		if fk == nil {
			return fmt.Errorf(`foreign-key "clinics_clinic_creds" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "clinics_clinic_creds" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *ClinicsQuery) loadDoctors(ctx context.Context, query *DoctorsQuery, nodes []*Clinics, init func(*Clinics), assign func(*Clinics, *Doctors)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Clinics)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Doctors(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(clinics.DoctorsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.clinics_doctors
		if fk == nil {
			return fmt.Errorf(`foreign-key "clinics_doctors" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "clinics_doctors" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *ClinicsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ClinicsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(clinics.Table, clinics.Columns, sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clinics.FieldID)
		for i := range fields {
			if fields[i] != clinics.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ClinicsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(clinics.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = clinics.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClinicsGroupBy is the group-by builder for Clinics entities.
type ClinicsGroupBy struct {
	selector
	build *ClinicsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ClinicsGroupBy) Aggregate(fns ...AggregateFunc) *ClinicsGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ClinicsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClinicsQuery, *ClinicsGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ClinicsGroupBy) sqlScan(ctx context.Context, root *ClinicsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClinicsSelect is the builder for selecting fields of Clinics entities.
type ClinicsSelect struct {
	*ClinicsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ClinicsSelect) Aggregate(fns ...AggregateFunc) *ClinicsSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ClinicsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClinicsQuery, *ClinicsSelect](ctx, cs.ClinicsQuery, cs, cs.inters, v)
}

func (cs *ClinicsSelect) sqlScan(ctx context.Context, root *ClinicsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
