// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
)

// ClinicCredsCreate is the builder for creating a ClinicCreds entity.
type ClinicCredsCreate struct {
	config
	mutation *ClinicCredsMutation
	hooks    []Hook
}

// SetSystem sets the "system" field.
func (ccc *ClinicCredsCreate) SetSystem(s string) *ClinicCredsCreate {
	ccc.mutation.SetSystem(s)
	return ccc
}

// SetUsername sets the "username" field.
func (ccc *ClinicCredsCreate) SetUsername(s string) *ClinicCredsCreate {
	ccc.mutation.SetUsername(s)
	return ccc
}

// SetPassword sets the "password" field.
func (ccc *ClinicCredsCreate) SetPassword(s string) *ClinicCredsCreate {
	ccc.mutation.SetPassword(s)
	return ccc
}

// SetClinicsID sets the "clinics" edge to the Clinics entity by ID.
func (ccc *ClinicCredsCreate) SetClinicsID(id int) *ClinicCredsCreate {
	ccc.mutation.SetClinicsID(id)
	return ccc
}

// SetClinics sets the "clinics" edge to the Clinics entity.
func (ccc *ClinicCredsCreate) SetClinics(c *Clinics) *ClinicCredsCreate {
	return ccc.SetClinicsID(c.ID)
}

// Mutation returns the ClinicCredsMutation object of the builder.
func (ccc *ClinicCredsCreate) Mutation() *ClinicCredsMutation {
	return ccc.mutation
}

// Save creates the ClinicCreds in the database.
func (ccc *ClinicCredsCreate) Save(ctx context.Context) (*ClinicCreds, error) {
	return withHooks(ctx, ccc.sqlSave, ccc.mutation, ccc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ccc *ClinicCredsCreate) SaveX(ctx context.Context) *ClinicCreds {
	v, err := ccc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccc *ClinicCredsCreate) Exec(ctx context.Context) error {
	_, err := ccc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccc *ClinicCredsCreate) ExecX(ctx context.Context) {
	if err := ccc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ccc *ClinicCredsCreate) check() error {
	if _, ok := ccc.mutation.System(); !ok {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required field "ClinicCreds.system"`)}
	}
	if v, ok := ccc.mutation.System(); ok {
		if err := cliniccreds.SystemValidator(v); err != nil {
			return &ValidationError{Name: "system", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.system": %w`, err)}
		}
	}
	if _, ok := ccc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "ClinicCreds.username"`)}
	}
	if v, ok := ccc.mutation.Username(); ok {
		if err := cliniccreds.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.username": %w`, err)}
		}
	}
	if _, ok := ccc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "ClinicCreds.password"`)}
	}
	if v, ok := ccc.mutation.Password(); ok {
		if err := cliniccreds.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ClinicCreds.password": %w`, err)}
		}
	}
	if len(ccc.mutation.ClinicsIDs()) == 0 {
		return &ValidationError{Name: "clinics", err: errors.New(`ent: missing required edge "ClinicCreds.clinics"`)}
	}
	return nil
}

func (ccc *ClinicCredsCreate) sqlSave(ctx context.Context) (*ClinicCreds, error) {
	if err := ccc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ccc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ccc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ccc.mutation.id = &_node.ID
	ccc.mutation.done = true
	return _node, nil
}

func (ccc *ClinicCredsCreate) createSpec() (*ClinicCreds, *sqlgraph.CreateSpec) {
	var (
		_node = &ClinicCreds{config: ccc.config}
		_spec = sqlgraph.NewCreateSpec(cliniccreds.Table, sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt))
	)
	if value, ok := ccc.mutation.System(); ok {
		_spec.SetField(cliniccreds.FieldSystem, field.TypeString, value)
		_node.System = value
	}
	if value, ok := ccc.mutation.Username(); ok {
		_spec.SetField(cliniccreds.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := ccc.mutation.Password(); ok {
		_spec.SetField(cliniccreds.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if nodes := ccc.mutation.ClinicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cliniccreds.ClinicsTable,
			Columns: []string{cliniccreds.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.clinics_clinic_creds = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClinicCredsCreateBulk is the builder for creating many ClinicCreds entities in bulk.
type ClinicCredsCreateBulk struct {
	config
	err      error
	builders []*ClinicCredsCreate
}

// Save creates the ClinicCreds entities in the database.
func (cccb *ClinicCredsCreateBulk) Save(ctx context.Context) ([]*ClinicCreds, error) {
	if cccb.err != nil {
		return nil, cccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cccb.builders))
	nodes := make([]*ClinicCreds, len(cccb.builders))
	mutators := make([]Mutator, len(cccb.builders))
	for i := range cccb.builders {
		func(i int, root context.Context) {
			builder := cccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClinicCredsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cccb *ClinicCredsCreateBulk) SaveX(ctx context.Context) []*ClinicCreds {
	v, err := cccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cccb *ClinicCredsCreateBulk) Exec(ctx context.Context) error {
	_, err := cccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cccb *ClinicCredsCreateBulk) ExecX(ctx context.Context) {
	if err := cccb.Exec(ctx); err != nil {
		panic(err)
	}
}
