// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
	regulatory "github.com/Chaitu35/claimeasy/backend/pkg/core"
)

// ClinicsCreate is the builder for creating a Clinics entity.
type ClinicsCreate struct {
	config
	mutation *ClinicsMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (cc *ClinicsCreate) SetName(s string) *ClinicsCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetCity sets the "city" field.
func (cc *ClinicsCreate) SetCity(s string) *ClinicsCreate {
	cc.mutation.SetCity(s)
	return cc
}

// SetRegulatory sets the "regulatory" field.
func (cc *ClinicsCreate) SetRegulatory(r regulatory.Regulatory) *ClinicsCreate {
	cc.mutation.SetRegulatory(r)
	return cc
}

// SetEmail sets the "email" field.
func (cc *ClinicsCreate) SetEmail(s string) *ClinicsCreate {
	cc.mutation.SetEmail(s)
	return cc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cc *ClinicsCreate) SetNillableEmail(s *string) *ClinicsCreate {
	if s != nil {
		cc.SetEmail(*s)
	}
	return cc
}

// SetPhone sets the "phone" field.
func (cc *ClinicsCreate) SetPhone(s string) *ClinicsCreate {
	cc.mutation.SetPhone(s)
	return cc
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (cc *ClinicsCreate) SetNillablePhone(s *string) *ClinicsCreate {
	if s != nil {
		cc.SetPhone(*s)
	}
	return cc
}

// SetFacilityID sets the "facilityID" field.
func (cc *ClinicsCreate) SetFacilityID(s string) *ClinicsCreate {
	cc.mutation.SetFacilityID(s)
	return cc
}

// AddClinicCredIDs adds the "clinic_creds" edge to the ClinicCreds entity by IDs.
func (cc *ClinicsCreate) AddClinicCredIDs(ids ...int) *ClinicsCreate {
	cc.mutation.AddClinicCredIDs(ids...)
	return cc
}

// AddClinicCreds adds the "clinic_creds" edges to the ClinicCreds entity.
func (cc *ClinicsCreate) AddClinicCreds(c ...*ClinicCreds) *ClinicsCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cc.AddClinicCredIDs(ids...)
}

// AddDoctorIDs adds the "doctors" edge to the Doctors entity by IDs.
func (cc *ClinicsCreate) AddDoctorIDs(ids ...int) *ClinicsCreate {
	cc.mutation.AddDoctorIDs(ids...)
	return cc
}

// AddDoctors adds the "doctors" edges to the Doctors entity.
func (cc *ClinicsCreate) AddDoctors(d ...*Doctors) *ClinicsCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return cc.AddDoctorIDs(ids...)
}

// Mutation returns the ClinicsMutation object of the builder.
func (cc *ClinicsCreate) Mutation() *ClinicsMutation {
	return cc.mutation
}

// Save creates the Clinics in the database.
func (cc *ClinicsCreate) Save(ctx context.Context) (*Clinics, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ClinicsCreate) SaveX(ctx context.Context) *Clinics {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ClinicsCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ClinicsCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ClinicsCreate) check() error {
	if _, ok := cc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Clinics.name"`)}
	}
	if v, ok := cc.mutation.Name(); ok {
		if err := clinics.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Clinics.name": %w`, err)}
		}
	}
	if _, ok := cc.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Clinics.city"`)}
	}
	if v, ok := cc.mutation.City(); ok {
		if err := clinics.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Clinics.city": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Regulatory(); !ok {
		return &ValidationError{Name: "regulatory", err: errors.New(`ent: missing required field "Clinics.regulatory"`)}
	}
	if v, ok := cc.mutation.Regulatory(); ok {
		if err := clinics.RegulatoryValidator(string(v)); err != nil {
			return &ValidationError{Name: "regulatory", err: fmt.Errorf(`ent: validator failed for field "Clinics.regulatory": %w`, err)}
		}
	}
	if _, ok := cc.mutation.FacilityID(); !ok {
		return &ValidationError{Name: "facilityID", err: errors.New(`ent: missing required field "Clinics.facilityID"`)}
	}
	return nil
}

func (cc *ClinicsCreate) sqlSave(ctx context.Context) (*Clinics, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ClinicsCreate) createSpec() (*Clinics, *sqlgraph.CreateSpec) {
	var (
		_node = &Clinics{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(clinics.Table, sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.Name(); ok {
		_spec.SetField(clinics.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cc.mutation.City(); ok {
		_spec.SetField(clinics.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := cc.mutation.Regulatory(); ok {
		_spec.SetField(clinics.FieldRegulatory, field.TypeString, value)
		_node.Regulatory = value
	}
	if value, ok := cc.mutation.Email(); ok {
		_spec.SetField(clinics.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := cc.mutation.Phone(); ok {
		_spec.SetField(clinics.FieldPhone, field.TypeString, value)
		_node.Phone = &value
	}
	if value, ok := cc.mutation.FacilityID(); ok {
		_spec.SetField(clinics.FieldFacilityID, field.TypeString, value)
		_node.FacilityID = value
	}
	if nodes := cc.mutation.ClinicCredsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.ClinicCredsTable,
			Columns: []string{clinics.ClinicCredsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.DoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.DoctorsTable,
			Columns: []string{clinics.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClinicsCreateBulk is the builder for creating many Clinics entities in bulk.
type ClinicsCreateBulk struct {
	config
	err      error
	builders []*ClinicsCreate
}

// Save creates the Clinics entities in the database.
func (ccb *ClinicsCreateBulk) Save(ctx context.Context) ([]*Clinics, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Clinics, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClinicsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ClinicsCreateBulk) SaveX(ctx context.Context) []*Clinics {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ClinicsCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ClinicsCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
