// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
)

// ClinicCreds is the model entity for the ClinicCreds schema.
type ClinicCreds struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// System holds the value of the "system" field.
	System string `json:"system,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"-"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClinicCredsQuery when eager-loading is set.
	Edges                ClinicCredsEdges `json:"edges"`
	clinics_clinic_creds *int
	selectValues         sql.SelectValues
}

// ClinicCredsEdges holds the relations/edges for other nodes in the graph.
type ClinicCredsEdges struct {
	// Clinics holds the value of the clinics edge.
	Clinics *Clinics `json:"clinics,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClinicsOrErr returns the Clinics value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClinicCredsEdges) ClinicsOrErr() (*Clinics, error) {
	if e.Clinics != nil {
		return e.Clinics, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: clinics.Label}
	}
	return nil, &NotLoadedError{edge: "clinics"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClinicCreds) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cliniccreds.FieldID:
			values[i] = new(sql.NullInt64)
		case cliniccreds.FieldSystem, cliniccreds.FieldUsername, cliniccreds.FieldPassword:
			values[i] = new(sql.NullString)
		case cliniccreds.ForeignKeys[0]: // clinics_clinic_creds
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClinicCreds fields.
func (cc *ClinicCreds) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cliniccreds.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cc.ID = int(value.Int64)
		case cliniccreds.FieldSystem:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system", values[i])
			} else if value.Valid {
				cc.System = value.String
			}
		case cliniccreds.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				cc.Username = value.String
			}
		case cliniccreds.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				cc.Password = value.String
			}
		case cliniccreds.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field clinics_clinic_creds", value)
			} else if value.Valid {
				cc.clinics_clinic_creds = new(int)
				*cc.clinics_clinic_creds = int(value.Int64)
			}
		default:
			cc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClinicCreds.
// This includes values selected through modifiers, order, etc.
func (cc *ClinicCreds) Value(name string) (ent.Value, error) {
	return cc.selectValues.Get(name)
}

// QueryClinics queries the "clinics" edge of the ClinicCreds entity.
func (cc *ClinicCreds) QueryClinics() *ClinicsQuery {
	return NewClinicCredsClient(cc.config).QueryClinics(cc)
}

// Update returns a builder for updating this ClinicCreds.
// Note that you need to call ClinicCreds.Unwrap() before calling this method if this ClinicCreds
// was returned from a transaction, and the transaction was committed or rolled back.
func (cc *ClinicCreds) Update() *ClinicCredsUpdateOne {
	return NewClinicCredsClient(cc.config).UpdateOne(cc)
}

// Unwrap unwraps the ClinicCreds entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cc *ClinicCreds) Unwrap() *ClinicCreds {
	_tx, ok := cc.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClinicCreds is not a transactional entity")
	}
	cc.config.driver = _tx.drv
	return cc
}

// String implements the fmt.Stringer.
func (cc *ClinicCreds) String() string {
	var builder strings.Builder
	builder.WriteString("ClinicCreds(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cc.ID))
	builder.WriteString("system=")
	builder.WriteString(cc.System)
	builder.WriteString(", ")
	builder.WriteString("username=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// ClinicCredsSlice is a parsable slice of ClinicCreds.
type ClinicCredsSlice []*ClinicCreds
