// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
	regulatory "github.com/Chaitu35/claimeasy/backend/pkg/core"
)

// ClinicsUpdate is the builder for updating Clinics entities.
type ClinicsUpdate struct {
	config
	hooks    []Hook
	mutation *ClinicsMutation
}

// Where appends a list predicates to the ClinicsUpdate builder.
func (cu *ClinicsUpdate) Where(ps ...predicate.Clinics) *ClinicsUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetName sets the "name" field.
func (cu *ClinicsUpdate) SetName(s string) *ClinicsUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *ClinicsUpdate) SetNillableName(s *string) *ClinicsUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// SetCity sets the "city" field.
func (cu *ClinicsUpdate) SetCity(s string) *ClinicsUpdate {
	cu.mutation.SetCity(s)
	return cu
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (cu *ClinicsUpdate) SetNillableCity(s *string) *ClinicsUpdate {
	if s != nil {
		cu.SetCity(*s)
	}
	return cu
}

// SetRegulatory sets the "regulatory" field.
func (cu *ClinicsUpdate) SetRegulatory(r regulatory.Regulatory) *ClinicsUpdate {
	cu.mutation.SetRegulatory(r)
	return cu
}

// SetNillableRegulatory sets the "regulatory" field if the given value is not nil.
func (cu *ClinicsUpdate) SetNillableRegulatory(r *regulatory.Regulatory) *ClinicsUpdate {
	if r != nil {
		cu.SetRegulatory(*r)
	}
	return cu
}

// SetEmail sets the "email" field.
func (cu *ClinicsUpdate) SetEmail(s string) *ClinicsUpdate {
	cu.mutation.SetEmail(s)
	return cu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cu *ClinicsUpdate) SetNillableEmail(s *string) *ClinicsUpdate {
	if s != nil {
		cu.SetEmail(*s)
	}
	return cu
}

// ClearEmail clears the value of the "email" field.
func (cu *ClinicsUpdate) ClearEmail() *ClinicsUpdate {
	cu.mutation.ClearEmail()
	return cu
}

// SetPhone sets the "phone" field.
func (cu *ClinicsUpdate) SetPhone(s string) *ClinicsUpdate {
	cu.mutation.SetPhone(s)
	return cu
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (cu *ClinicsUpdate) SetNillablePhone(s *string) *ClinicsUpdate {
	if s != nil {
		cu.SetPhone(*s)
	}
	return cu
}

// ClearPhone clears the value of the "phone" field.
func (cu *ClinicsUpdate) ClearPhone() *ClinicsUpdate {
	cu.mutation.ClearPhone()
	return cu
}

// SetFacilityID sets the "facilityID" field.
func (cu *ClinicsUpdate) SetFacilityID(s string) *ClinicsUpdate {
	cu.mutation.SetFacilityID(s)
	return cu
}

// SetNillableFacilityID sets the "facilityID" field if the given value is not nil.
func (cu *ClinicsUpdate) SetNillableFacilityID(s *string) *ClinicsUpdate {
	if s != nil {
		cu.SetFacilityID(*s)
	}
	return cu
}

// AddClinicCredIDs adds the "clinic_creds" edge to the ClinicCreds entity by IDs.
func (cu *ClinicsUpdate) AddClinicCredIDs(ids ...int) *ClinicsUpdate {
	cu.mutation.AddClinicCredIDs(ids...)
	return cu
}

// AddClinicCreds adds the "clinic_creds" edges to the ClinicCreds entity.
func (cu *ClinicsUpdate) AddClinicCreds(c ...*ClinicCreds) *ClinicsUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddClinicCredIDs(ids...)
}

// AddDoctorIDs adds the "doctors" edge to the Doctors entity by IDs.
func (cu *ClinicsUpdate) AddDoctorIDs(ids ...int) *ClinicsUpdate {
	cu.mutation.AddDoctorIDs(ids...)
	return cu
}

// AddDoctors adds the "doctors" edges to the Doctors entity.
func (cu *ClinicsUpdate) AddDoctors(d ...*Doctors) *ClinicsUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return cu.AddDoctorIDs(ids...)
}

// Mutation returns the ClinicsMutation object of the builder.
func (cu *ClinicsUpdate) Mutation() *ClinicsMutation {
	return cu.mutation
}

// ClearClinicCreds clears all "clinic_creds" edges to the ClinicCreds entity.
func (cu *ClinicsUpdate) ClearClinicCreds() *ClinicsUpdate {
	cu.mutation.ClearClinicCreds()
	return cu
}

// RemoveClinicCredIDs removes the "clinic_creds" edge to ClinicCreds entities by IDs.
func (cu *ClinicsUpdate) RemoveClinicCredIDs(ids ...int) *ClinicsUpdate {
	cu.mutation.RemoveClinicCredIDs(ids...)
	return cu
}

// RemoveClinicCreds removes "clinic_creds" edges to ClinicCreds entities.
func (cu *ClinicsUpdate) RemoveClinicCreds(c ...*ClinicCreds) *ClinicsUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveClinicCredIDs(ids...)
}

// ClearDoctors clears all "doctors" edges to the Doctors entity.
func (cu *ClinicsUpdate) ClearDoctors() *ClinicsUpdate {
	cu.mutation.ClearDoctors()
	return cu
}

// RemoveDoctorIDs removes the "doctors" edge to Doctors entities by IDs.
func (cu *ClinicsUpdate) RemoveDoctorIDs(ids ...int) *ClinicsUpdate {
	cu.mutation.RemoveDoctorIDs(ids...)
	return cu
}

// RemoveDoctors removes "doctors" edges to Doctors entities.
func (cu *ClinicsUpdate) RemoveDoctors(d ...*Doctors) *ClinicsUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return cu.RemoveDoctorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClinicsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClinicsUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClinicsUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClinicsUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ClinicsUpdate) check() error {
	if v, ok := cu.mutation.Name(); ok {
		if err := clinics.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Clinics.name": %w`, err)}
		}
	}
	if v, ok := cu.mutation.City(); ok {
		if err := clinics.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Clinics.city": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Regulatory(); ok {
		if err := clinics.RegulatoryValidator(string(v)); err != nil {
			return &ValidationError{Name: "regulatory", err: fmt.Errorf(`ent: validator failed for field "Clinics.regulatory": %w`, err)}
		}
	}
	return nil
}

func (cu *ClinicsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(clinics.Table, clinics.Columns, sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(clinics.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.City(); ok {
		_spec.SetField(clinics.FieldCity, field.TypeString, value)
	}
	if value, ok := cu.mutation.Regulatory(); ok {
		_spec.SetField(clinics.FieldRegulatory, field.TypeString, value)
	}
	if value, ok := cu.mutation.Email(); ok {
		_spec.SetField(clinics.FieldEmail, field.TypeString, value)
	}
	if cu.mutation.EmailCleared() {
		_spec.ClearField(clinics.FieldEmail, field.TypeString)
	}
	if value, ok := cu.mutation.Phone(); ok {
		_spec.SetField(clinics.FieldPhone, field.TypeString, value)
	}
	if cu.mutation.PhoneCleared() {
		_spec.ClearField(clinics.FieldPhone, field.TypeString)
	}
	if value, ok := cu.mutation.FacilityID(); ok {
		_spec.SetField(clinics.FieldFacilityID, field.TypeString, value)
	}
	if cu.mutation.ClinicCredsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.ClinicCredsTable,
			Columns: []string{clinics.ClinicCredsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedClinicCredsIDs(); len(nodes) > 0 && !cu.mutation.ClinicCredsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.ClinicCredsTable,
			Columns: []string{clinics.ClinicCredsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ClinicCredsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.ClinicCredsTable,
			Columns: []string{clinics.ClinicCredsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.DoctorsTable,
			Columns: []string{clinics.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedDoctorsIDs(); len(nodes) > 0 && !cu.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.DoctorsTable,
			Columns: []string{clinics.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.DoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.DoctorsTable,
			Columns: []string{clinics.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clinics.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ClinicsUpdateOne is the builder for updating a single Clinics entity.
type ClinicsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClinicsMutation
}

// SetName sets the "name" field.
func (cuo *ClinicsUpdateOne) SetName(s string) *ClinicsUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *ClinicsUpdateOne) SetNillableName(s *string) *ClinicsUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// SetCity sets the "city" field.
func (cuo *ClinicsUpdateOne) SetCity(s string) *ClinicsUpdateOne {
	cuo.mutation.SetCity(s)
	return cuo
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (cuo *ClinicsUpdateOne) SetNillableCity(s *string) *ClinicsUpdateOne {
	if s != nil {
		cuo.SetCity(*s)
	}
	return cuo
}

// SetRegulatory sets the "regulatory" field.
func (cuo *ClinicsUpdateOne) SetRegulatory(r regulatory.Regulatory) *ClinicsUpdateOne {
	cuo.mutation.SetRegulatory(r)
	return cuo
}

// SetNillableRegulatory sets the "regulatory" field if the given value is not nil.
func (cuo *ClinicsUpdateOne) SetNillableRegulatory(r *regulatory.Regulatory) *ClinicsUpdateOne {
	if r != nil {
		cuo.SetRegulatory(*r)
	}
	return cuo
}

// SetEmail sets the "email" field.
func (cuo *ClinicsUpdateOne) SetEmail(s string) *ClinicsUpdateOne {
	cuo.mutation.SetEmail(s)
	return cuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cuo *ClinicsUpdateOne) SetNillableEmail(s *string) *ClinicsUpdateOne {
	if s != nil {
		cuo.SetEmail(*s)
	}
	return cuo
}

// ClearEmail clears the value of the "email" field.
func (cuo *ClinicsUpdateOne) ClearEmail() *ClinicsUpdateOne {
	cuo.mutation.ClearEmail()
	return cuo
}

// SetPhone sets the "phone" field.
func (cuo *ClinicsUpdateOne) SetPhone(s string) *ClinicsUpdateOne {
	cuo.mutation.SetPhone(s)
	return cuo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (cuo *ClinicsUpdateOne) SetNillablePhone(s *string) *ClinicsUpdateOne {
	if s != nil {
		cuo.SetPhone(*s)
	}
	return cuo
}

// ClearPhone clears the value of the "phone" field.
func (cuo *ClinicsUpdateOne) ClearPhone() *ClinicsUpdateOne {
	cuo.mutation.ClearPhone()
	return cuo
}

// SetFacilityID sets the "facilityID" field.
func (cuo *ClinicsUpdateOne) SetFacilityID(s string) *ClinicsUpdateOne {
	cuo.mutation.SetFacilityID(s)
	return cuo
}

// SetNillableFacilityID sets the "facilityID" field if the given value is not nil.
func (cuo *ClinicsUpdateOne) SetNillableFacilityID(s *string) *ClinicsUpdateOne {
	if s != nil {
		cuo.SetFacilityID(*s)
	}
	return cuo
}

// AddClinicCredIDs adds the "clinic_creds" edge to the ClinicCreds entity by IDs.
func (cuo *ClinicsUpdateOne) AddClinicCredIDs(ids ...int) *ClinicsUpdateOne {
	cuo.mutation.AddClinicCredIDs(ids...)
	return cuo
}

// AddClinicCreds adds the "clinic_creds" edges to the ClinicCreds entity.
func (cuo *ClinicsUpdateOne) AddClinicCreds(c ...*ClinicCreds) *ClinicsUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddClinicCredIDs(ids...)
}

// AddDoctorIDs adds the "doctors" edge to the Doctors entity by IDs.
func (cuo *ClinicsUpdateOne) AddDoctorIDs(ids ...int) *ClinicsUpdateOne {
	cuo.mutation.AddDoctorIDs(ids...)
	return cuo
}

// AddDoctors adds the "doctors" edges to the Doctors entity.
func (cuo *ClinicsUpdateOne) AddDoctors(d ...*Doctors) *ClinicsUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return cuo.AddDoctorIDs(ids...)
}

// Mutation returns the ClinicsMutation object of the builder.
func (cuo *ClinicsUpdateOne) Mutation() *ClinicsMutation {
	return cuo.mutation
}

// ClearClinicCreds clears all "clinic_creds" edges to the ClinicCreds entity.
func (cuo *ClinicsUpdateOne) ClearClinicCreds() *ClinicsUpdateOne {
	cuo.mutation.ClearClinicCreds()
	return cuo
}

// RemoveClinicCredIDs removes the "clinic_creds" edge to ClinicCreds entities by IDs.
func (cuo *ClinicsUpdateOne) RemoveClinicCredIDs(ids ...int) *ClinicsUpdateOne {
	cuo.mutation.RemoveClinicCredIDs(ids...)
	return cuo
}

// RemoveClinicCreds removes "clinic_creds" edges to ClinicCreds entities.
func (cuo *ClinicsUpdateOne) RemoveClinicCreds(c ...*ClinicCreds) *ClinicsUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveClinicCredIDs(ids...)
}

// ClearDoctors clears all "doctors" edges to the Doctors entity.
func (cuo *ClinicsUpdateOne) ClearDoctors() *ClinicsUpdateOne {
	cuo.mutation.ClearDoctors()
	return cuo
}

// RemoveDoctorIDs removes the "doctors" edge to Doctors entities by IDs.
func (cuo *ClinicsUpdateOne) RemoveDoctorIDs(ids ...int) *ClinicsUpdateOne {
	cuo.mutation.RemoveDoctorIDs(ids...)
	return cuo
}

// RemoveDoctors removes "doctors" edges to Doctors entities.
func (cuo *ClinicsUpdateOne) RemoveDoctors(d ...*Doctors) *ClinicsUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return cuo.RemoveDoctorIDs(ids...)
}

// Where appends a list predicates to the ClinicsUpdate builder.
func (cuo *ClinicsUpdateOne) Where(ps ...predicate.Clinics) *ClinicsUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClinicsUpdateOne) Select(field string, fields ...string) *ClinicsUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Clinics entity.
func (cuo *ClinicsUpdateOne) Save(ctx context.Context) (*Clinics, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClinicsUpdateOne) SaveX(ctx context.Context) *Clinics {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClinicsUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClinicsUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ClinicsUpdateOne) check() error {
	if v, ok := cuo.mutation.Name(); ok {
		if err := clinics.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Clinics.name": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.City(); ok {
		if err := clinics.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Clinics.city": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Regulatory(); ok {
		if err := clinics.RegulatoryValidator(string(v)); err != nil {
			return &ValidationError{Name: "regulatory", err: fmt.Errorf(`ent: validator failed for field "Clinics.regulatory": %w`, err)}
		}
	}
	return nil
}

func (cuo *ClinicsUpdateOne) sqlSave(ctx context.Context) (_node *Clinics, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clinics.Table, clinics.Columns, sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Clinics.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clinics.FieldID)
		for _, f := range fields {
			if !clinics.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clinics.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(clinics.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.City(); ok {
		_spec.SetField(clinics.FieldCity, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Regulatory(); ok {
		_spec.SetField(clinics.FieldRegulatory, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Email(); ok {
		_spec.SetField(clinics.FieldEmail, field.TypeString, value)
	}
	if cuo.mutation.EmailCleared() {
		_spec.ClearField(clinics.FieldEmail, field.TypeString)
	}
	if value, ok := cuo.mutation.Phone(); ok {
		_spec.SetField(clinics.FieldPhone, field.TypeString, value)
	}
	if cuo.mutation.PhoneCleared() {
		_spec.ClearField(clinics.FieldPhone, field.TypeString)
	}
	if value, ok := cuo.mutation.FacilityID(); ok {
		_spec.SetField(clinics.FieldFacilityID, field.TypeString, value)
	}
	if cuo.mutation.ClinicCredsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.ClinicCredsTable,
			Columns: []string{clinics.ClinicCredsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedClinicCredsIDs(); len(nodes) > 0 && !cuo.mutation.ClinicCredsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.ClinicCredsTable,
			Columns: []string{clinics.ClinicCredsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ClinicCredsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.ClinicCredsTable,
			Columns: []string{clinics.ClinicCredsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.DoctorsTable,
			Columns: []string{clinics.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedDoctorsIDs(); len(nodes) > 0 && !cuo.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.DoctorsTable,
			Columns: []string{clinics.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.DoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clinics.DoctorsTable,
			Columns: []string{clinics.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Clinics{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clinics.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
