// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	regulatory "github.com/Chaitu35/claimeasy/backend/pkg/core"
)

// Clinics is the model entity for the Clinics schema.
type Clinics struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// City holds the value of the "city" field.
	City string `json:"city,omitempty"`
	// Regulatory holds the value of the "regulatory" field.
	Regulatory regulatory.Regulatory `json:"regulatory,omitempty"`
	// Email holds the value of the "email" field.
	Email *string `json:"email,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone *string `json:"phone,omitempty"`
	// FacilityID holds the value of the "facilityID" field.
	FacilityID string `json:"facilityID,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClinicsQuery when eager-loading is set.
	Edges        ClinicsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClinicsEdges holds the relations/edges for other nodes in the graph.
type ClinicsEdges struct {
	// ClinicCreds holds the value of the clinic_creds edge.
	ClinicCreds []*ClinicCreds `json:"clinic_creds,omitempty"`
	// Doctors holds the value of the doctors edge.
	Doctors []*Doctors `json:"doctors,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ClinicCredsOrErr returns the ClinicCreds value or an error if the edge
// was not loaded in eager-loading.
func (e ClinicsEdges) ClinicCredsOrErr() ([]*ClinicCreds, error) {
	if e.loadedTypes[0] {
		return e.ClinicCreds, nil
	}
	return nil, &NotLoadedError{edge: "clinic_creds"}
}

// DoctorsOrErr returns the Doctors value or an error if the edge
// was not loaded in eager-loading.
func (e ClinicsEdges) DoctorsOrErr() ([]*Doctors, error) {
	if e.loadedTypes[1] {
		return e.Doctors, nil
	}
	return nil, &NotLoadedError{edge: "doctors"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Clinics) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clinics.FieldID:
			values[i] = new(sql.NullInt64)
		case clinics.FieldName, clinics.FieldCity, clinics.FieldRegulatory, clinics.FieldEmail, clinics.FieldPhone, clinics.FieldFacilityID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Clinics fields.
func (c *Clinics) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clinics.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case clinics.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case clinics.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				c.City = value.String
			}
		case clinics.FieldRegulatory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field regulatory", values[i])
			} else if value.Valid {
				c.Regulatory = regulatory.Regulatory(value.String)
			}
		case clinics.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				c.Email = new(string)
				*c.Email = value.String
			}
		case clinics.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				c.Phone = new(string)
				*c.Phone = value.String
			}
		case clinics.FieldFacilityID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field facilityID", values[i])
			} else if value.Valid {
				c.FacilityID = value.String
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Clinics.
// This includes values selected through modifiers, order, etc.
func (c *Clinics) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryClinicCreds queries the "clinic_creds" edge of the Clinics entity.
func (c *Clinics) QueryClinicCreds() *ClinicCredsQuery {
	return NewClinicsClient(c.config).QueryClinicCreds(c)
}

// QueryDoctors queries the "doctors" edge of the Clinics entity.
func (c *Clinics) QueryDoctors() *DoctorsQuery {
	return NewClinicsClient(c.config).QueryDoctors(c)
}

// Update returns a builder for updating this Clinics.
// Note that you need to call Clinics.Unwrap() before calling this method if this Clinics
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Clinics) Update() *ClinicsUpdateOne {
	return NewClinicsClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Clinics entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Clinics) Unwrap() *Clinics {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Clinics is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Clinics) String() string {
	var builder strings.Builder
	builder.WriteString("Clinics(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("name=")
	builder.WriteString(c.Name)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(c.City)
	builder.WriteString(", ")
	builder.WriteString("regulatory=")
	builder.WriteString(fmt.Sprintf("%v", c.Regulatory))
	builder.WriteString(", ")
	if v := c.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := c.Phone; v != nil {
		builder.WriteString("phone=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("facilityID=")
	builder.WriteString(c.FacilityID)
	builder.WriteByte(')')
	return builder.String()
}

// ClinicsSlice is a parsable slice of Clinics.
type ClinicsSlice []*Clinics
