// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// ClinicCredsQuery is the builder for querying ClinicCreds entities.
type ClinicCredsQuery struct {
	config
	ctx         *QueryContext
	order       []cliniccreds.OrderOption
	inters      []Interceptor
	predicates  []predicate.ClinicCreds
	withClinics *ClinicsQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClinicCredsQuery builder.
func (ccq *ClinicCredsQuery) Where(ps ...predicate.ClinicCreds) *ClinicCredsQuery {
	ccq.predicates = append(ccq.predicates, ps...)
	return ccq
}

// Limit the number of records to be returned by this query.
func (ccq *ClinicCredsQuery) Limit(limit int) *ClinicCredsQuery {
	ccq.ctx.Limit = &limit
	return ccq
}

// Offset to start from.
func (ccq *ClinicCredsQuery) Offset(offset int) *ClinicCredsQuery {
	ccq.ctx.Offset = &offset
	return ccq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ccq *ClinicCredsQuery) Unique(unique bool) *ClinicCredsQuery {
	ccq.ctx.Unique = &unique
	return ccq
}

// Order specifies how the records should be ordered.
func (ccq *ClinicCredsQuery) Order(o ...cliniccreds.OrderOption) *ClinicCredsQuery {
	ccq.order = append(ccq.order, o...)
	return ccq
}

// QueryClinics chains the current query on the "clinics" edge.
func (ccq *ClinicCredsQuery) QueryClinics() *ClinicsQuery {
	query := (&ClinicsClient{config: ccq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ccq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ccq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cliniccreds.Table, cliniccreds.FieldID, selector),
			sqlgraph.To(clinics.Table, clinics.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cliniccreds.ClinicsTable, cliniccreds.ClinicsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ccq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ClinicCreds entity from the query.
// Returns a *NotFoundError when no ClinicCreds was found.
func (ccq *ClinicCredsQuery) First(ctx context.Context) (*ClinicCreds, error) {
	nodes, err := ccq.Limit(1).All(setContextOp(ctx, ccq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cliniccreds.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ccq *ClinicCredsQuery) FirstX(ctx context.Context) *ClinicCreds {
	node, err := ccq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ClinicCreds ID from the query.
// Returns a *NotFoundError when no ClinicCreds ID was found.
func (ccq *ClinicCredsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ccq.Limit(1).IDs(setContextOp(ctx, ccq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cliniccreds.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ccq *ClinicCredsQuery) FirstIDX(ctx context.Context) int {
	id, err := ccq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ClinicCreds entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ClinicCreds entity is found.
// Returns a *NotFoundError when no ClinicCreds entities are found.
func (ccq *ClinicCredsQuery) Only(ctx context.Context) (*ClinicCreds, error) {
	nodes, err := ccq.Limit(2).All(setContextOp(ctx, ccq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cliniccreds.Label}
	default:
		return nil, &NotSingularError{cliniccreds.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ccq *ClinicCredsQuery) OnlyX(ctx context.Context) *ClinicCreds {
	node, err := ccq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ClinicCreds ID in the query.
// Returns a *NotSingularError when more than one ClinicCreds ID is found.
// Returns a *NotFoundError when no entities are found.
func (ccq *ClinicCredsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ccq.Limit(2).IDs(setContextOp(ctx, ccq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cliniccreds.Label}
	default:
		err = &NotSingularError{cliniccreds.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ccq *ClinicCredsQuery) OnlyIDX(ctx context.Context) int {
	id, err := ccq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ClinicCredsSlice.
func (ccq *ClinicCredsQuery) All(ctx context.Context) ([]*ClinicCreds, error) {
	ctx = setContextOp(ctx, ccq.ctx, ent.OpQueryAll)
	if err := ccq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ClinicCreds, *ClinicCredsQuery]()
	return withInterceptors[[]*ClinicCreds](ctx, ccq, qr, ccq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ccq *ClinicCredsQuery) AllX(ctx context.Context) []*ClinicCreds {
	nodes, err := ccq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ClinicCreds IDs.
func (ccq *ClinicCredsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ccq.ctx.Unique == nil && ccq.path != nil {
		ccq.Unique(true)
	}
	ctx = setContextOp(ctx, ccq.ctx, ent.OpQueryIDs)
	if err = ccq.Select(cliniccreds.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ccq *ClinicCredsQuery) IDsX(ctx context.Context) []int {
	ids, err := ccq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ccq *ClinicCredsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ccq.ctx, ent.OpQueryCount)
	if err := ccq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ccq, querierCount[*ClinicCredsQuery](), ccq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ccq *ClinicCredsQuery) CountX(ctx context.Context) int {
	count, err := ccq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ccq *ClinicCredsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ccq.ctx, ent.OpQueryExist)
	switch _, err := ccq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ccq *ClinicCredsQuery) ExistX(ctx context.Context) bool {
	exist, err := ccq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClinicCredsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ccq *ClinicCredsQuery) Clone() *ClinicCredsQuery {
	if ccq == nil {
		return nil
	}
	return &ClinicCredsQuery{
		config:      ccq.config,
		ctx:         ccq.ctx.Clone(),
		order:       append([]cliniccreds.OrderOption{}, ccq.order...),
		inters:      append([]Interceptor{}, ccq.inters...),
		predicates:  append([]predicate.ClinicCreds{}, ccq.predicates...),
		withClinics: ccq.withClinics.Clone(),
		// clone intermediate query.
		sql:  ccq.sql.Clone(),
		path: ccq.path,
	}
}

// WithClinics tells the query-builder to eager-load the nodes that are connected to
// the "clinics" edge. The optional arguments are used to configure the query builder of the edge.
func (ccq *ClinicCredsQuery) WithClinics(opts ...func(*ClinicsQuery)) *ClinicCredsQuery {
	query := (&ClinicsClient{config: ccq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ccq.withClinics = query
	return ccq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		System string `json:"system,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ClinicCreds.Query().
//		GroupBy(cliniccreds.FieldSystem).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ccq *ClinicCredsQuery) GroupBy(field string, fields ...string) *ClinicCredsGroupBy {
	ccq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClinicCredsGroupBy{build: ccq}
	grbuild.flds = &ccq.ctx.Fields
	grbuild.label = cliniccreds.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		System string `json:"system,omitempty"`
//	}
//
//	client.ClinicCreds.Query().
//		Select(cliniccreds.FieldSystem).
//		Scan(ctx, &v)
func (ccq *ClinicCredsQuery) Select(fields ...string) *ClinicCredsSelect {
	ccq.ctx.Fields = append(ccq.ctx.Fields, fields...)
	sbuild := &ClinicCredsSelect{ClinicCredsQuery: ccq}
	sbuild.label = cliniccreds.Label
	sbuild.flds, sbuild.scan = &ccq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClinicCredsSelect configured with the given aggregations.
func (ccq *ClinicCredsQuery) Aggregate(fns ...AggregateFunc) *ClinicCredsSelect {
	return ccq.Select().Aggregate(fns...)
}

func (ccq *ClinicCredsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ccq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ccq); err != nil {
				return err
			}
		}
	}
	for _, f := range ccq.ctx.Fields {
		if !cliniccreds.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ccq.path != nil {
		prev, err := ccq.path(ctx)
		if err != nil {
			return err
		}
		ccq.sql = prev
	}
	return nil
}

func (ccq *ClinicCredsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ClinicCreds, error) {
	var (
		nodes       = []*ClinicCreds{}
		withFKs     = ccq.withFKs
		_spec       = ccq.querySpec()
		loadedTypes = [1]bool{
			ccq.withClinics != nil,
		}
	)
	if ccq.withClinics != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, cliniccreds.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ClinicCreds).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ClinicCreds{config: ccq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ccq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ccq.withClinics; query != nil {
		if err := ccq.loadClinics(ctx, query, nodes, nil,
			func(n *ClinicCreds, e *Clinics) { n.Edges.Clinics = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ccq *ClinicCredsQuery) loadClinics(ctx context.Context, query *ClinicsQuery, nodes []*ClinicCreds, init func(*ClinicCreds), assign func(*ClinicCreds, *Clinics)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ClinicCreds)
	for i := range nodes {
		if nodes[i].clinics_clinic_creds == nil {
			continue
		}
		fk := *nodes[i].clinics_clinic_creds
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(clinics.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "clinics_clinic_creds" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ccq *ClinicCredsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ccq.querySpec()
	_spec.Node.Columns = ccq.ctx.Fields
	if len(ccq.ctx.Fields) > 0 {
		_spec.Unique = ccq.ctx.Unique != nil && *ccq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ccq.driver, _spec)
}

func (ccq *ClinicCredsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cliniccreds.Table, cliniccreds.Columns, sqlgraph.NewFieldSpec(cliniccreds.FieldID, field.TypeInt))
	_spec.From = ccq.sql
	if unique := ccq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ccq.path != nil {
		_spec.Unique = true
	}
	if fields := ccq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cliniccreds.FieldID)
		for i := range fields {
			if fields[i] != cliniccreds.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ccq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ccq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ccq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ccq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ccq *ClinicCredsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ccq.driver.Dialect())
	t1 := builder.Table(cliniccreds.Table)
	columns := ccq.ctx.Fields
	if len(columns) == 0 {
		columns = cliniccreds.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ccq.sql != nil {
		selector = ccq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ccq.ctx.Unique != nil && *ccq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ccq.predicates {
		p(selector)
	}
	for _, p := range ccq.order {
		p(selector)
	}
	if offset := ccq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ccq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClinicCredsGroupBy is the group-by builder for ClinicCreds entities.
type ClinicCredsGroupBy struct {
	selector
	build *ClinicCredsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ccgb *ClinicCredsGroupBy) Aggregate(fns ...AggregateFunc) *ClinicCredsGroupBy {
	ccgb.fns = append(ccgb.fns, fns...)
	return ccgb
}

// Scan applies the selector query and scans the result into the given value.
func (ccgb *ClinicCredsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ccgb.build.ctx, ent.OpQueryGroupBy)
	if err := ccgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClinicCredsQuery, *ClinicCredsGroupBy](ctx, ccgb.build, ccgb, ccgb.build.inters, v)
}

func (ccgb *ClinicCredsGroupBy) sqlScan(ctx context.Context, root *ClinicCredsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ccgb.fns))
	for _, fn := range ccgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ccgb.flds)+len(ccgb.fns))
		for _, f := range *ccgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ccgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ccgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClinicCredsSelect is the builder for selecting fields of ClinicCreds entities.
type ClinicCredsSelect struct {
	*ClinicCredsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ccs *ClinicCredsSelect) Aggregate(fns ...AggregateFunc) *ClinicCredsSelect {
	ccs.fns = append(ccs.fns, fns...)
	return ccs
}

// Scan applies the selector query and scans the result into the given value.
func (ccs *ClinicCredsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ccs.ctx, ent.OpQuerySelect)
	if err := ccs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClinicCredsQuery, *ClinicCredsSelect](ctx, ccs.ClinicCredsQuery, ccs, ccs.inters, v)
}

func (ccs *ClinicCredsSelect) sqlScan(ctx context.Context, root *ClinicCredsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ccs.fns))
	for _, fn := range ccs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ccs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ccs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
