// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
)

// DoctorsCreate is the builder for creating a Doctors entity.
type DoctorsCreate struct {
	config
	mutation *DoctorsMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (dc *DoctorsCreate) SetName(s string) *DoctorsCreate {
	dc.mutation.SetName(s)
	return dc
}

// SetSpecialization sets the "specialization" field.
func (dc *DoctorsCreate) SetSpecialization(s string) *DoctorsCreate {
	dc.mutation.SetSpecialization(s)
	return dc
}

// SetLicense sets the "license" field.
func (dc *DoctorsCreate) SetLicense(s string) *DoctorsCreate {
	dc.mutation.SetLicense(s)
	return dc
}

// SetClinicsID sets the "clinics" edge to the Clinics entity by ID.
func (dc *DoctorsCreate) SetClinicsID(id int) *DoctorsCreate {
	dc.mutation.SetClinicsID(id)
	return dc
}

// SetClinics sets the "clinics" edge to the Clinics entity.
func (dc *DoctorsCreate) SetClinics(c *Clinics) *DoctorsCreate {
	return dc.SetClinicsID(c.ID)
}

// Mutation returns the DoctorsMutation object of the builder.
func (dc *DoctorsCreate) Mutation() *DoctorsMutation {
	return dc.mutation
}

// Save creates the Doctors in the database.
func (dc *DoctorsCreate) Save(ctx context.Context) (*Doctors, error) {
	return withHooks(ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DoctorsCreate) SaveX(ctx context.Context) *Doctors {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DoctorsCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DoctorsCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DoctorsCreate) check() error {
	if _, ok := dc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Doctors.name"`)}
	}
	if v, ok := dc.mutation.Name(); ok {
		if err := doctors.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Doctors.name": %w`, err)}
		}
	}
	if _, ok := dc.mutation.Specialization(); !ok {
		return &ValidationError{Name: "specialization", err: errors.New(`ent: missing required field "Doctors.specialization"`)}
	}
	if v, ok := dc.mutation.Specialization(); ok {
		if err := doctors.SpecializationValidator(v); err != nil {
			return &ValidationError{Name: "specialization", err: fmt.Errorf(`ent: validator failed for field "Doctors.specialization": %w`, err)}
		}
	}
	if _, ok := dc.mutation.License(); !ok {
		return &ValidationError{Name: "license", err: errors.New(`ent: missing required field "Doctors.license"`)}
	}
	if v, ok := dc.mutation.License(); ok {
		if err := doctors.LicenseValidator(v); err != nil {
			return &ValidationError{Name: "license", err: fmt.Errorf(`ent: validator failed for field "Doctors.license": %w`, err)}
		}
	}
	if len(dc.mutation.ClinicsIDs()) == 0 {
		return &ValidationError{Name: "clinics", err: errors.New(`ent: missing required edge "Doctors.clinics"`)}
	}
	return nil
}

func (dc *DoctorsCreate) sqlSave(ctx context.Context) (*Doctors, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DoctorsCreate) createSpec() (*Doctors, *sqlgraph.CreateSpec) {
	var (
		_node = &Doctors{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(doctors.Table, sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt))
	)
	if value, ok := dc.mutation.Name(); ok {
		_spec.SetField(doctors.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dc.mutation.Specialization(); ok {
		_spec.SetField(doctors.FieldSpecialization, field.TypeString, value)
		_node.Specialization = value
	}
	if value, ok := dc.mutation.License(); ok {
		_spec.SetField(doctors.FieldLicense, field.TypeString, value)
		_node.License = value
	}
	if nodes := dc.mutation.ClinicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctors.ClinicsTable,
			Columns: []string{doctors.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.clinics_doctors = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DoctorsCreateBulk is the builder for creating many Doctors entities in bulk.
type DoctorsCreateBulk struct {
	config
	err      error
	builders []*DoctorsCreate
}

// Save creates the Doctors entities in the database.
func (dcb *DoctorsCreateBulk) Save(ctx context.Context) ([]*Doctors, error) {
	if dcb.err != nil {
		return nil, dcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Doctors, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DoctorsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DoctorsCreateBulk) SaveX(ctx context.Context) []*Doctors {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DoctorsCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DoctorsCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
