// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
)

// Doctors is the model entity for the Doctors schema.
type Doctors struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Specialization holds the value of the "specialization" field.
	Specialization string `json:"specialization,omitempty"`
	// License holds the value of the "license" field.
	License string `json:"license,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DoctorsQuery when eager-loading is set.
	Edges           DoctorsEdges `json:"edges"`
	clinics_doctors *int
	selectValues    sql.SelectValues
}

// DoctorsEdges holds the relations/edges for other nodes in the graph.
type DoctorsEdges struct {
	// Clinics holds the value of the clinics edge.
	Clinics *Clinics `json:"clinics,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClinicsOrErr returns the Clinics value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DoctorsEdges) ClinicsOrErr() (*Clinics, error) {
	if e.Clinics != nil {
		return e.Clinics, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: clinics.Label}
	}
	return nil, &NotLoadedError{edge: "clinics"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Doctors) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case doctors.FieldID:
			values[i] = new(sql.NullInt64)
		case doctors.FieldName, doctors.FieldSpecialization, doctors.FieldLicense:
			values[i] = new(sql.NullString)
		case doctors.ForeignKeys[0]: // clinics_doctors
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Doctors fields.
func (d *Doctors) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case doctors.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		case doctors.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				d.Name = value.String
			}
		case doctors.FieldSpecialization:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field specialization", values[i])
			} else if value.Valid {
				d.Specialization = value.String
			}
		case doctors.FieldLicense:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license", values[i])
			} else if value.Valid {
				d.License = value.String
			}
		case doctors.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field clinics_doctors", value)
			} else if value.Valid {
				d.clinics_doctors = new(int)
				*d.clinics_doctors = int(value.Int64)
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Doctors.
// This includes values selected through modifiers, order, etc.
func (d *Doctors) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryClinics queries the "clinics" edge of the Doctors entity.
func (d *Doctors) QueryClinics() *ClinicsQuery {
	return NewDoctorsClient(d.config).QueryClinics(d)
}

// Update returns a builder for updating this Doctors.
// Note that you need to call Doctors.Unwrap() before calling this method if this Doctors
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Doctors) Update() *DoctorsUpdateOne {
	return NewDoctorsClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Doctors entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Doctors) Unwrap() *Doctors {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Doctors is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Doctors) String() string {
	var builder strings.Builder
	builder.WriteString("Doctors(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("name=")
	builder.WriteString(d.Name)
	builder.WriteString(", ")
	builder.WriteString("specialization=")
	builder.WriteString(d.Specialization)
	builder.WriteString(", ")
	builder.WriteString("license=")
	builder.WriteString(d.License)
	builder.WriteByte(')')
	return builder.String()
}

// DoctorsSlice is a parsable slice of Doctors.
type DoctorsSlice []*Doctors
