// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// DoctorsQuery is the builder for querying Doctors entities.
type DoctorsQuery struct {
	config
	ctx         *QueryContext
	order       []doctors.OrderOption
	inters      []Interceptor
	predicates  []predicate.Doctors
	withClinics *ClinicsQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DoctorsQuery builder.
func (dq *DoctorsQuery) Where(ps ...predicate.Doctors) *DoctorsQuery {
	dq.predicates = append(dq.predicates, ps...)
	return dq
}

// Limit the number of records to be returned by this query.
func (dq *DoctorsQuery) Limit(limit int) *DoctorsQuery {
	dq.ctx.Limit = &limit
	return dq
}

// Offset to start from.
func (dq *DoctorsQuery) Offset(offset int) *DoctorsQuery {
	dq.ctx.Offset = &offset
	return dq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dq *DoctorsQuery) Unique(unique bool) *DoctorsQuery {
	dq.ctx.Unique = &unique
	return dq
}

// Order specifies how the records should be ordered.
func (dq *DoctorsQuery) Order(o ...doctors.OrderOption) *DoctorsQuery {
	dq.order = append(dq.order, o...)
	return dq
}

// QueryClinics chains the current query on the "clinics" edge.
func (dq *DoctorsQuery) QueryClinics() *ClinicsQuery {
	query := (&ClinicsClient{config: dq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(doctors.Table, doctors.FieldID, selector),
			sqlgraph.To(clinics.Table, clinics.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, doctors.ClinicsTable, doctors.ClinicsColumn),
		)
		fromU = sqlgraph.SetNeighbors(dq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Doctors entity from the query.
// Returns a *NotFoundError when no Doctors was found.
func (dq *DoctorsQuery) First(ctx context.Context) (*Doctors, error) {
	nodes, err := dq.Limit(1).All(setContextOp(ctx, dq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{doctors.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dq *DoctorsQuery) FirstX(ctx context.Context) *Doctors {
	node, err := dq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Doctors ID from the query.
// Returns a *NotFoundError when no Doctors ID was found.
func (dq *DoctorsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dq.Limit(1).IDs(setContextOp(ctx, dq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{doctors.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dq *DoctorsQuery) FirstIDX(ctx context.Context) int {
	id, err := dq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Doctors entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Doctors entity is found.
// Returns a *NotFoundError when no Doctors entities are found.
func (dq *DoctorsQuery) Only(ctx context.Context) (*Doctors, error) {
	nodes, err := dq.Limit(2).All(setContextOp(ctx, dq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{doctors.Label}
	default:
		return nil, &NotSingularError{doctors.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dq *DoctorsQuery) OnlyX(ctx context.Context) *Doctors {
	node, err := dq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Doctors ID in the query.
// Returns a *NotSingularError when more than one Doctors ID is found.
// Returns a *NotFoundError when no entities are found.
func (dq *DoctorsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dq.Limit(2).IDs(setContextOp(ctx, dq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{doctors.Label}
	default:
		err = &NotSingularError{doctors.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dq *DoctorsQuery) OnlyIDX(ctx context.Context) int {
	id, err := dq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DoctorsSlice.
func (dq *DoctorsQuery) All(ctx context.Context) ([]*Doctors, error) {
	ctx = setContextOp(ctx, dq.ctx, ent.OpQueryAll)
	if err := dq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Doctors, *DoctorsQuery]()
	return withInterceptors[[]*Doctors](ctx, dq, qr, dq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dq *DoctorsQuery) AllX(ctx context.Context) []*Doctors {
	nodes, err := dq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Doctors IDs.
func (dq *DoctorsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if dq.ctx.Unique == nil && dq.path != nil {
		dq.Unique(true)
	}
	ctx = setContextOp(ctx, dq.ctx, ent.OpQueryIDs)
	if err = dq.Select(doctors.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dq *DoctorsQuery) IDsX(ctx context.Context) []int {
	ids, err := dq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dq *DoctorsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dq.ctx, ent.OpQueryCount)
	if err := dq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dq, querierCount[*DoctorsQuery](), dq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dq *DoctorsQuery) CountX(ctx context.Context) int {
	count, err := dq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dq *DoctorsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dq.ctx, ent.OpQueryExist)
	switch _, err := dq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dq *DoctorsQuery) ExistX(ctx context.Context) bool {
	exist, err := dq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DoctorsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dq *DoctorsQuery) Clone() *DoctorsQuery {
	if dq == nil {
		return nil
	}
	return &DoctorsQuery{
		config:      dq.config,
		ctx:         dq.ctx.Clone(),
		order:       append([]doctors.OrderOption{}, dq.order...),
		inters:      append([]Interceptor{}, dq.inters...),
		predicates:  append([]predicate.Doctors{}, dq.predicates...),
		withClinics: dq.withClinics.Clone(),
		// clone intermediate query.
		sql:  dq.sql.Clone(),
		path: dq.path,
	}
}

// WithClinics tells the query-builder to eager-load the nodes that are connected to
// the "clinics" edge. The optional arguments are used to configure the query builder of the edge.
func (dq *DoctorsQuery) WithClinics(opts ...func(*ClinicsQuery)) *DoctorsQuery {
	query := (&ClinicsClient{config: dq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dq.withClinics = query
	return dq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Doctors.Query().
//		GroupBy(doctors.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dq *DoctorsQuery) GroupBy(field string, fields ...string) *DoctorsGroupBy {
	dq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DoctorsGroupBy{build: dq}
	grbuild.flds = &dq.ctx.Fields
	grbuild.label = doctors.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Doctors.Query().
//		Select(doctors.FieldName).
//		Scan(ctx, &v)
func (dq *DoctorsQuery) Select(fields ...string) *DoctorsSelect {
	dq.ctx.Fields = append(dq.ctx.Fields, fields...)
	sbuild := &DoctorsSelect{DoctorsQuery: dq}
	sbuild.label = doctors.Label
	sbuild.flds, sbuild.scan = &dq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DoctorsSelect configured with the given aggregations.
func (dq *DoctorsQuery) Aggregate(fns ...AggregateFunc) *DoctorsSelect {
	return dq.Select().Aggregate(fns...)
}

func (dq *DoctorsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dq); err != nil {
				return err
			}
		}
	}
	for _, f := range dq.ctx.Fields {
		if !doctors.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dq.path != nil {
		prev, err := dq.path(ctx)
		if err != nil {
			return err
		}
		dq.sql = prev
	}
	return nil
}

func (dq *DoctorsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Doctors, error) {
	var (
		nodes       = []*Doctors{}
		withFKs     = dq.withFKs
		_spec       = dq.querySpec()
		loadedTypes = [1]bool{
			dq.withClinics != nil,
		}
	)
	if dq.withClinics != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, doctors.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Doctors).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Doctors{config: dq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dq.withClinics; query != nil {
		if err := dq.loadClinics(ctx, query, nodes, nil,
			func(n *Doctors, e *Clinics) { n.Edges.Clinics = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dq *DoctorsQuery) loadClinics(ctx context.Context, query *ClinicsQuery, nodes []*Doctors, init func(*Doctors), assign func(*Doctors, *Clinics)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Doctors)
	for i := range nodes {
		if nodes[i].clinics_doctors == nil {
			continue
		}
		fk := *nodes[i].clinics_doctors
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(clinics.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "clinics_doctors" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dq *DoctorsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dq.querySpec()
	_spec.Node.Columns = dq.ctx.Fields
	if len(dq.ctx.Fields) > 0 {
		_spec.Unique = dq.ctx.Unique != nil && *dq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dq.driver, _spec)
}

func (dq *DoctorsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(doctors.Table, doctors.Columns, sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt))
	_spec.From = dq.sql
	if unique := dq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dq.path != nil {
		_spec.Unique = true
	}
	if fields := dq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, doctors.FieldID)
		for i := range fields {
			if fields[i] != doctors.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dq *DoctorsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dq.driver.Dialect())
	t1 := builder.Table(doctors.Table)
	columns := dq.ctx.Fields
	if len(columns) == 0 {
		columns = doctors.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dq.sql != nil {
		selector = dq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dq.ctx.Unique != nil && *dq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dq.predicates {
		p(selector)
	}
	for _, p := range dq.order {
		p(selector)
	}
	if offset := dq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DoctorsGroupBy is the group-by builder for Doctors entities.
type DoctorsGroupBy struct {
	selector
	build *DoctorsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dgb *DoctorsGroupBy) Aggregate(fns ...AggregateFunc) *DoctorsGroupBy {
	dgb.fns = append(dgb.fns, fns...)
	return dgb
}

// Scan applies the selector query and scans the result into the given value.
func (dgb *DoctorsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dgb.build.ctx, ent.OpQueryGroupBy)
	if err := dgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DoctorsQuery, *DoctorsGroupBy](ctx, dgb.build, dgb, dgb.build.inters, v)
}

func (dgb *DoctorsGroupBy) sqlScan(ctx context.Context, root *DoctorsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dgb.fns))
	for _, fn := range dgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dgb.flds)+len(dgb.fns))
		for _, f := range *dgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DoctorsSelect is the builder for selecting fields of Doctors entities.
type DoctorsSelect struct {
	*DoctorsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ds *DoctorsSelect) Aggregate(fns ...AggregateFunc) *DoctorsSelect {
	ds.fns = append(ds.fns, fns...)
	return ds
}

// Scan applies the selector query and scans the result into the given value.
func (ds *DoctorsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ds.ctx, ent.OpQuerySelect)
	if err := ds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DoctorsQuery, *DoctorsSelect](ctx, ds.DoctorsQuery, ds, ds.inters, v)
}

func (ds *DoctorsSelect) sqlScan(ctx context.Context, root *DoctorsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ds.fns))
	for _, fn := range ds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
