// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// DoctorsUpdate is the builder for updating Doctors entities.
type DoctorsUpdate struct {
	config
	hooks    []Hook
	mutation *DoctorsMutation
}

// Where appends a list predicates to the DoctorsUpdate builder.
func (du *DoctorsUpdate) Where(ps ...predicate.Doctors) *DoctorsUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DoctorsUpdate) SetName(s string) *DoctorsUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DoctorsUpdate) SetNillableName(s *string) *DoctorsUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// SetSpecialization sets the "specialization" field.
func (du *DoctorsUpdate) SetSpecialization(s string) *DoctorsUpdate {
	du.mutation.SetSpecialization(s)
	return du
}

// SetNillableSpecialization sets the "specialization" field if the given value is not nil.
func (du *DoctorsUpdate) SetNillableSpecialization(s *string) *DoctorsUpdate {
	if s != nil {
		du.SetSpecialization(*s)
	}
	return du
}

// SetLicense sets the "license" field.
func (du *DoctorsUpdate) SetLicense(s string) *DoctorsUpdate {
	du.mutation.SetLicense(s)
	return du
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (du *DoctorsUpdate) SetNillableLicense(s *string) *DoctorsUpdate {
	if s != nil {
		du.SetLicense(*s)
	}
	return du
}

// SetClinicsID sets the "clinics" edge to the Clinics entity by ID.
func (du *DoctorsUpdate) SetClinicsID(id int) *DoctorsUpdate {
	du.mutation.SetClinicsID(id)
	return du
}

// SetClinics sets the "clinics" edge to the Clinics entity.
func (du *DoctorsUpdate) SetClinics(c *Clinics) *DoctorsUpdate {
	return du.SetClinicsID(c.ID)
}

// Mutation returns the DoctorsMutation object of the builder.
func (du *DoctorsUpdate) Mutation() *DoctorsMutation {
	return du.mutation
}

// ClearClinics clears the "clinics" edge to the Clinics entity.
func (du *DoctorsUpdate) ClearClinics() *DoctorsUpdate {
	du.mutation.ClearClinics()
	return du
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DoctorsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DoctorsUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DoctorsUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DoctorsUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (du *DoctorsUpdate) check() error {
	if v, ok := du.mutation.Name(); ok {
		if err := doctors.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Doctors.name": %w`, err)}
		}
	}
	if v, ok := du.mutation.Specialization(); ok {
		if err := doctors.SpecializationValidator(v); err != nil {
			return &ValidationError{Name: "specialization", err: fmt.Errorf(`ent: validator failed for field "Doctors.specialization": %w`, err)}
		}
	}
	if v, ok := du.mutation.License(); ok {
		if err := doctors.LicenseValidator(v); err != nil {
			return &ValidationError{Name: "license", err: fmt.Errorf(`ent: validator failed for field "Doctors.license": %w`, err)}
		}
	}
	if du.mutation.ClinicsCleared() && len(du.mutation.ClinicsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Doctors.clinics"`)
	}
	return nil
}

func (du *DoctorsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := du.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(doctors.Table, doctors.Columns, sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(doctors.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.Specialization(); ok {
		_spec.SetField(doctors.FieldSpecialization, field.TypeString, value)
	}
	if value, ok := du.mutation.License(); ok {
		_spec.SetField(doctors.FieldLicense, field.TypeString, value)
	}
	if du.mutation.ClinicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctors.ClinicsTable,
			Columns: []string{doctors.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.ClinicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctors.ClinicsTable,
			Columns: []string{doctors.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{doctors.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DoctorsUpdateOne is the builder for updating a single Doctors entity.
type DoctorsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DoctorsMutation
}

// SetName sets the "name" field.
func (duo *DoctorsUpdateOne) SetName(s string) *DoctorsUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DoctorsUpdateOne) SetNillableName(s *string) *DoctorsUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// SetSpecialization sets the "specialization" field.
func (duo *DoctorsUpdateOne) SetSpecialization(s string) *DoctorsUpdateOne {
	duo.mutation.SetSpecialization(s)
	return duo
}

// SetNillableSpecialization sets the "specialization" field if the given value is not nil.
func (duo *DoctorsUpdateOne) SetNillableSpecialization(s *string) *DoctorsUpdateOne {
	if s != nil {
		duo.SetSpecialization(*s)
	}
	return duo
}

// SetLicense sets the "license" field.
func (duo *DoctorsUpdateOne) SetLicense(s string) *DoctorsUpdateOne {
	duo.mutation.SetLicense(s)
	return duo
}

// SetNillableLicense sets the "license" field if the given value is not nil.
func (duo *DoctorsUpdateOne) SetNillableLicense(s *string) *DoctorsUpdateOne {
	if s != nil {
		duo.SetLicense(*s)
	}
	return duo
}

// SetClinicsID sets the "clinics" edge to the Clinics entity by ID.
func (duo *DoctorsUpdateOne) SetClinicsID(id int) *DoctorsUpdateOne {
	duo.mutation.SetClinicsID(id)
	return duo
}

// SetClinics sets the "clinics" edge to the Clinics entity.
func (duo *DoctorsUpdateOne) SetClinics(c *Clinics) *DoctorsUpdateOne {
	return duo.SetClinicsID(c.ID)
}

// Mutation returns the DoctorsMutation object of the builder.
func (duo *DoctorsUpdateOne) Mutation() *DoctorsMutation {
	return duo.mutation
}

// ClearClinics clears the "clinics" edge to the Clinics entity.
func (duo *DoctorsUpdateOne) ClearClinics() *DoctorsUpdateOne {
	duo.mutation.ClearClinics()
	return duo
}

// Where appends a list predicates to the DoctorsUpdate builder.
func (duo *DoctorsUpdateOne) Where(ps ...predicate.Doctors) *DoctorsUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DoctorsUpdateOne) Select(field string, fields ...string) *DoctorsUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Doctors entity.
func (duo *DoctorsUpdateOne) Save(ctx context.Context) (*Doctors, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DoctorsUpdateOne) SaveX(ctx context.Context) *Doctors {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DoctorsUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DoctorsUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (duo *DoctorsUpdateOne) check() error {
	if v, ok := duo.mutation.Name(); ok {
		if err := doctors.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Doctors.name": %w`, err)}
		}
	}
	if v, ok := duo.mutation.Specialization(); ok {
		if err := doctors.SpecializationValidator(v); err != nil {
			return &ValidationError{Name: "specialization", err: fmt.Errorf(`ent: validator failed for field "Doctors.specialization": %w`, err)}
		}
	}
	if v, ok := duo.mutation.License(); ok {
		if err := doctors.LicenseValidator(v); err != nil {
			return &ValidationError{Name: "license", err: fmt.Errorf(`ent: validator failed for field "Doctors.license": %w`, err)}
		}
	}
	if duo.mutation.ClinicsCleared() && len(duo.mutation.ClinicsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Doctors.clinics"`)
	}
	return nil
}

func (duo *DoctorsUpdateOne) sqlSave(ctx context.Context) (_node *Doctors, err error) {
	if err := duo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(doctors.Table, doctors.Columns, sqlgraph.NewFieldSpec(doctors.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Doctors.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, doctors.FieldID)
		for _, f := range fields {
			if !doctors.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != doctors.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(doctors.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.Specialization(); ok {
		_spec.SetField(doctors.FieldSpecialization, field.TypeString, value)
	}
	if value, ok := duo.mutation.License(); ok {
		_spec.SetField(doctors.FieldLicense, field.TypeString, value)
	}
	if duo.mutation.ClinicsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctors.ClinicsTable,
			Columns: []string{doctors.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.ClinicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctors.ClinicsTable,
			Columns: []string{doctors.ClinicsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinics.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Doctors{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{doctors.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
