// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Chaitu35/claimeasy/backend/ent/permissions"
	"github.com/Chaitu35/claimeasy/backend/ent/user"
)

// Permissions is the model entity for the Permissions schema.
type Permissions struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Module holds the value of the "module" field.
	Module string `json:"module,omitempty"`
	// CanView holds the value of the "can_view" field.
	CanView bool `json:"can_view,omitempty"`
	// CanCreate holds the value of the "can_create" field.
	CanCreate bool `json:"can_create,omitempty"`
	// CanEdit holds the value of the "can_edit" field.
	CanEdit bool `json:"can_edit,omitempty"`
	// CanDelete holds the value of the "can_delete" field.
	CanDelete bool `json:"can_delete,omitempty"`
	// CanExport holds the value of the "can_export" field.
	CanExport bool `json:"can_export,omitempty"`
	// CanPrint holds the value of the "can_print" field.
	CanPrint bool `json:"can_print,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PermissionsQuery when eager-loading is set.
	Edges            PermissionsEdges `json:"edges"`
	user_permissions *int
	selectValues     sql.SelectValues
}

// PermissionsEdges holds the relations/edges for other nodes in the graph.
type PermissionsEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PermissionsEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Permissions) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case permissions.FieldCanView, permissions.FieldCanCreate, permissions.FieldCanEdit, permissions.FieldCanDelete, permissions.FieldCanExport, permissions.FieldCanPrint:
			values[i] = new(sql.NullBool)
		case permissions.FieldID:
			values[i] = new(sql.NullInt64)
		case permissions.FieldModule:
			values[i] = new(sql.NullString)
		case permissions.ForeignKeys[0]: // user_permissions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Permissions fields.
func (pe *Permissions) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case permissions.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pe.ID = int(value.Int64)
		case permissions.FieldModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module", values[i])
			} else if value.Valid {
				pe.Module = value.String
			}
		case permissions.FieldCanView:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_view", values[i])
			} else if value.Valid {
				pe.CanView = value.Bool
			}
		case permissions.FieldCanCreate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_create", values[i])
			} else if value.Valid {
				pe.CanCreate = value.Bool
			}
		case permissions.FieldCanEdit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_edit", values[i])
			} else if value.Valid {
				pe.CanEdit = value.Bool
			}
		case permissions.FieldCanDelete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_delete", values[i])
			} else if value.Valid {
				pe.CanDelete = value.Bool
			}
		case permissions.FieldCanExport:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_export", values[i])
			} else if value.Valid {
				pe.CanExport = value.Bool
			}
		case permissions.FieldCanPrint:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_print", values[i])
			} else if value.Valid {
				pe.CanPrint = value.Bool
			}
		case permissions.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_permissions", value)
			} else if value.Valid {
				pe.user_permissions = new(int)
				*pe.user_permissions = int(value.Int64)
			}
		default:
			pe.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Permissions.
// This includes values selected through modifiers, order, etc.
func (pe *Permissions) Value(name string) (ent.Value, error) {
	return pe.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Permissions entity.
func (pe *Permissions) QueryUser() *UserQuery {
	return NewPermissionsClient(pe.config).QueryUser(pe)
}

// Update returns a builder for updating this Permissions.
// Note that you need to call Permissions.Unwrap() before calling this method if this Permissions
// was returned from a transaction, and the transaction was committed or rolled back.
func (pe *Permissions) Update() *PermissionsUpdateOne {
	return NewPermissionsClient(pe.config).UpdateOne(pe)
}

// Unwrap unwraps the Permissions entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pe *Permissions) Unwrap() *Permissions {
	_tx, ok := pe.config.driver.(*txDriver)
	if !ok {
		panic("ent: Permissions is not a transactional entity")
	}
	pe.config.driver = _tx.drv
	return pe
}

// String implements the fmt.Stringer.
func (pe *Permissions) String() string {
	var builder strings.Builder
	builder.WriteString("Permissions(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pe.ID))
	builder.WriteString("module=")
	builder.WriteString(pe.Module)
	builder.WriteString(", ")
	builder.WriteString("can_view=")
	builder.WriteString(fmt.Sprintf("%v", pe.CanView))
	builder.WriteString(", ")
	builder.WriteString("can_create=")
	builder.WriteString(fmt.Sprintf("%v", pe.CanCreate))
	builder.WriteString(", ")
	builder.WriteString("can_edit=")
	builder.WriteString(fmt.Sprintf("%v", pe.CanEdit))
	builder.WriteString(", ")
	builder.WriteString("can_delete=")
	builder.WriteString(fmt.Sprintf("%v", pe.CanDelete))
	builder.WriteString(", ")
	builder.WriteString("can_export=")
	builder.WriteString(fmt.Sprintf("%v", pe.CanExport))
	builder.WriteString(", ")
	builder.WriteString("can_print=")
	builder.WriteString(fmt.Sprintf("%v", pe.CanPrint))
	builder.WriteByte(')')
	return builder.String()
}

// PermissionsSlice is a parsable slice of Permissions.
type PermissionsSlice []*Permissions
