// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/permissions"
	"github.com/Chaitu35/claimeasy/backend/ent/user"
)

// PermissionsCreate is the builder for creating a Permissions entity.
type PermissionsCreate struct {
	config
	mutation *PermissionsMutation
	hooks    []Hook
}

// SetModule sets the "module" field.
func (pc *PermissionsCreate) SetModule(s string) *PermissionsCreate {
	pc.mutation.SetModule(s)
	return pc
}

// SetCanView sets the "can_view" field.
func (pc *PermissionsCreate) SetCanView(b bool) *PermissionsCreate {
	pc.mutation.SetCanView(b)
	return pc
}

// SetNillableCanView sets the "can_view" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableCanView(b *bool) *PermissionsCreate {
	if b != nil {
		pc.SetCanView(*b)
	}
	return pc
}

// SetCanCreate sets the "can_create" field.
func (pc *PermissionsCreate) SetCanCreate(b bool) *PermissionsCreate {
	pc.mutation.SetCanCreate(b)
	return pc
}

// SetNillableCanCreate sets the "can_create" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableCanCreate(b *bool) *PermissionsCreate {
	if b != nil {
		pc.SetCanCreate(*b)
	}
	return pc
}

// SetCanEdit sets the "can_edit" field.
func (pc *PermissionsCreate) SetCanEdit(b bool) *PermissionsCreate {
	pc.mutation.SetCanEdit(b)
	return pc
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableCanEdit(b *bool) *PermissionsCreate {
	if b != nil {
		pc.SetCanEdit(*b)
	}
	return pc
}

// SetCanDelete sets the "can_delete" field.
func (pc *PermissionsCreate) SetCanDelete(b bool) *PermissionsCreate {
	pc.mutation.SetCanDelete(b)
	return pc
}

// SetNillableCanDelete sets the "can_delete" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableCanDelete(b *bool) *PermissionsCreate {
	if b != nil {
		pc.SetCanDelete(*b)
	}
	return pc
}

// SetCanExport sets the "can_export" field.
func (pc *PermissionsCreate) SetCanExport(b bool) *PermissionsCreate {
	pc.mutation.SetCanExport(b)
	return pc
}

// SetNillableCanExport sets the "can_export" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableCanExport(b *bool) *PermissionsCreate {
	if b != nil {
		pc.SetCanExport(*b)
	}
	return pc
}

// SetCanPrint sets the "can_print" field.
func (pc *PermissionsCreate) SetCanPrint(b bool) *PermissionsCreate {
	pc.mutation.SetCanPrint(b)
	return pc
}

// SetNillableCanPrint sets the "can_print" field if the given value is not nil.
func (pc *PermissionsCreate) SetNillableCanPrint(b *bool) *PermissionsCreate {
	if b != nil {
		pc.SetCanPrint(*b)
	}
	return pc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (pc *PermissionsCreate) SetUserID(id int) *PermissionsCreate {
	pc.mutation.SetUserID(id)
	return pc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (pc *PermissionsCreate) SetNillableUserID(id *int) *PermissionsCreate {
	if id != nil {
		pc = pc.SetUserID(*id)
	}
	return pc
}

// SetUser sets the "user" edge to the User entity.
func (pc *PermissionsCreate) SetUser(u *User) *PermissionsCreate {
	return pc.SetUserID(u.ID)
}

// Mutation returns the PermissionsMutation object of the builder.
func (pc *PermissionsCreate) Mutation() *PermissionsMutation {
	return pc.mutation
}

// Save creates the Permissions in the database.
func (pc *PermissionsCreate) Save(ctx context.Context) (*Permissions, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PermissionsCreate) SaveX(ctx context.Context) *Permissions {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PermissionsCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PermissionsCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PermissionsCreate) defaults() {
	if _, ok := pc.mutation.CanView(); !ok {
		v := permissions.DefaultCanView
		pc.mutation.SetCanView(v)
	}
	if _, ok := pc.mutation.CanCreate(); !ok {
		v := permissions.DefaultCanCreate
		pc.mutation.SetCanCreate(v)
	}
	if _, ok := pc.mutation.CanEdit(); !ok {
		v := permissions.DefaultCanEdit
		pc.mutation.SetCanEdit(v)
	}
	if _, ok := pc.mutation.CanDelete(); !ok {
		v := permissions.DefaultCanDelete
		pc.mutation.SetCanDelete(v)
	}
	if _, ok := pc.mutation.CanExport(); !ok {
		v := permissions.DefaultCanExport
		pc.mutation.SetCanExport(v)
	}
	if _, ok := pc.mutation.CanPrint(); !ok {
		v := permissions.DefaultCanPrint
		pc.mutation.SetCanPrint(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PermissionsCreate) check() error {
	if _, ok := pc.mutation.Module(); !ok {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required field "Permissions.module"`)}
	}
	if _, ok := pc.mutation.CanView(); !ok {
		return &ValidationError{Name: "can_view", err: errors.New(`ent: missing required field "Permissions.can_view"`)}
	}
	if _, ok := pc.mutation.CanCreate(); !ok {
		return &ValidationError{Name: "can_create", err: errors.New(`ent: missing required field "Permissions.can_create"`)}
	}
	if _, ok := pc.mutation.CanEdit(); !ok {
		return &ValidationError{Name: "can_edit", err: errors.New(`ent: missing required field "Permissions.can_edit"`)}
	}
	if _, ok := pc.mutation.CanDelete(); !ok {
		return &ValidationError{Name: "can_delete", err: errors.New(`ent: missing required field "Permissions.can_delete"`)}
	}
	if _, ok := pc.mutation.CanExport(); !ok {
		return &ValidationError{Name: "can_export", err: errors.New(`ent: missing required field "Permissions.can_export"`)}
	}
	if _, ok := pc.mutation.CanPrint(); !ok {
		return &ValidationError{Name: "can_print", err: errors.New(`ent: missing required field "Permissions.can_print"`)}
	}
	return nil
}

func (pc *PermissionsCreate) sqlSave(ctx context.Context) (*Permissions, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PermissionsCreate) createSpec() (*Permissions, *sqlgraph.CreateSpec) {
	var (
		_node = &Permissions{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(permissions.Table, sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Module(); ok {
		_spec.SetField(permissions.FieldModule, field.TypeString, value)
		_node.Module = value
	}
	if value, ok := pc.mutation.CanView(); ok {
		_spec.SetField(permissions.FieldCanView, field.TypeBool, value)
		_node.CanView = value
	}
	if value, ok := pc.mutation.CanCreate(); ok {
		_spec.SetField(permissions.FieldCanCreate, field.TypeBool, value)
		_node.CanCreate = value
	}
	if value, ok := pc.mutation.CanEdit(); ok {
		_spec.SetField(permissions.FieldCanEdit, field.TypeBool, value)
		_node.CanEdit = value
	}
	if value, ok := pc.mutation.CanDelete(); ok {
		_spec.SetField(permissions.FieldCanDelete, field.TypeBool, value)
		_node.CanDelete = value
	}
	if value, ok := pc.mutation.CanExport(); ok {
		_spec.SetField(permissions.FieldCanExport, field.TypeBool, value)
		_node.CanExport = value
	}
	if value, ok := pc.mutation.CanPrint(); ok {
		_spec.SetField(permissions.FieldCanPrint, field.TypeBool, value)
		_node.CanPrint = value
	}
	if nodes := pc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissions.UserTable,
			Columns: []string{permissions.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_permissions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PermissionsCreateBulk is the builder for creating many Permissions entities in bulk.
type PermissionsCreateBulk struct {
	config
	err      error
	builders []*PermissionsCreate
}

// Save creates the Permissions entities in the database.
func (pcb *PermissionsCreateBulk) Save(ctx context.Context) ([]*Permissions, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Permissions, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PermissionsCreateBulk) SaveX(ctx context.Context) []*Permissions {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PermissionsCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PermissionsCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
