// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/permissions"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
	"github.com/Chaitu35/claimeasy/backend/ent/user"
)

// PermissionsUpdate is the builder for updating Permissions entities.
type PermissionsUpdate struct {
	config
	hooks    []Hook
	mutation *PermissionsMutation
}

// Where appends a list predicates to the PermissionsUpdate builder.
func (pu *PermissionsUpdate) Where(ps ...predicate.Permissions) *PermissionsUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetModule sets the "module" field.
func (pu *PermissionsUpdate) SetModule(s string) *PermissionsUpdate {
	pu.mutation.SetModule(s)
	return pu
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableModule(s *string) *PermissionsUpdate {
	if s != nil {
		pu.SetModule(*s)
	}
	return pu
}

// SetCanView sets the "can_view" field.
func (pu *PermissionsUpdate) SetCanView(b bool) *PermissionsUpdate {
	pu.mutation.SetCanView(b)
	return pu
}

// SetNillableCanView sets the "can_view" field if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableCanView(b *bool) *PermissionsUpdate {
	if b != nil {
		pu.SetCanView(*b)
	}
	return pu
}

// SetCanCreate sets the "can_create" field.
func (pu *PermissionsUpdate) SetCanCreate(b bool) *PermissionsUpdate {
	pu.mutation.SetCanCreate(b)
	return pu
}

// SetNillableCanCreate sets the "can_create" field if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableCanCreate(b *bool) *PermissionsUpdate {
	if b != nil {
		pu.SetCanCreate(*b)
	}
	return pu
}

// SetCanEdit sets the "can_edit" field.
func (pu *PermissionsUpdate) SetCanEdit(b bool) *PermissionsUpdate {
	pu.mutation.SetCanEdit(b)
	return pu
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableCanEdit(b *bool) *PermissionsUpdate {
	if b != nil {
		pu.SetCanEdit(*b)
	}
	return pu
}

// SetCanDelete sets the "can_delete" field.
func (pu *PermissionsUpdate) SetCanDelete(b bool) *PermissionsUpdate {
	pu.mutation.SetCanDelete(b)
	return pu
}

// SetNillableCanDelete sets the "can_delete" field if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableCanDelete(b *bool) *PermissionsUpdate {
	if b != nil {
		pu.SetCanDelete(*b)
	}
	return pu
}

// SetCanExport sets the "can_export" field.
func (pu *PermissionsUpdate) SetCanExport(b bool) *PermissionsUpdate {
	pu.mutation.SetCanExport(b)
	return pu
}

// SetNillableCanExport sets the "can_export" field if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableCanExport(b *bool) *PermissionsUpdate {
	if b != nil {
		pu.SetCanExport(*b)
	}
	return pu
}

// SetCanPrint sets the "can_print" field.
func (pu *PermissionsUpdate) SetCanPrint(b bool) *PermissionsUpdate {
	pu.mutation.SetCanPrint(b)
	return pu
}

// SetNillableCanPrint sets the "can_print" field if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableCanPrint(b *bool) *PermissionsUpdate {
	if b != nil {
		pu.SetCanPrint(*b)
	}
	return pu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (pu *PermissionsUpdate) SetUserID(id int) *PermissionsUpdate {
	pu.mutation.SetUserID(id)
	return pu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (pu *PermissionsUpdate) SetNillableUserID(id *int) *PermissionsUpdate {
	if id != nil {
		pu = pu.SetUserID(*id)
	}
	return pu
}

// SetUser sets the "user" edge to the User entity.
func (pu *PermissionsUpdate) SetUser(u *User) *PermissionsUpdate {
	return pu.SetUserID(u.ID)
}

// Mutation returns the PermissionsMutation object of the builder.
func (pu *PermissionsUpdate) Mutation() *PermissionsMutation {
	return pu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pu *PermissionsUpdate) ClearUser() *PermissionsUpdate {
	pu.mutation.ClearUser()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PermissionsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PermissionsUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PermissionsUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PermissionsUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PermissionsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(permissions.Table, permissions.Columns, sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Module(); ok {
		_spec.SetField(permissions.FieldModule, field.TypeString, value)
	}
	if value, ok := pu.mutation.CanView(); ok {
		_spec.SetField(permissions.FieldCanView, field.TypeBool, value)
	}
	if value, ok := pu.mutation.CanCreate(); ok {
		_spec.SetField(permissions.FieldCanCreate, field.TypeBool, value)
	}
	if value, ok := pu.mutation.CanEdit(); ok {
		_spec.SetField(permissions.FieldCanEdit, field.TypeBool, value)
	}
	if value, ok := pu.mutation.CanDelete(); ok {
		_spec.SetField(permissions.FieldCanDelete, field.TypeBool, value)
	}
	if value, ok := pu.mutation.CanExport(); ok {
		_spec.SetField(permissions.FieldCanExport, field.TypeBool, value)
	}
	if value, ok := pu.mutation.CanPrint(); ok {
		_spec.SetField(permissions.FieldCanPrint, field.TypeBool, value)
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissions.UserTable,
			Columns: []string{permissions.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissions.UserTable,
			Columns: []string{permissions.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PermissionsUpdateOne is the builder for updating a single Permissions entity.
type PermissionsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PermissionsMutation
}

// SetModule sets the "module" field.
func (puo *PermissionsUpdateOne) SetModule(s string) *PermissionsUpdateOne {
	puo.mutation.SetModule(s)
	return puo
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableModule(s *string) *PermissionsUpdateOne {
	if s != nil {
		puo.SetModule(*s)
	}
	return puo
}

// SetCanView sets the "can_view" field.
func (puo *PermissionsUpdateOne) SetCanView(b bool) *PermissionsUpdateOne {
	puo.mutation.SetCanView(b)
	return puo
}

// SetNillableCanView sets the "can_view" field if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableCanView(b *bool) *PermissionsUpdateOne {
	if b != nil {
		puo.SetCanView(*b)
	}
	return puo
}

// SetCanCreate sets the "can_create" field.
func (puo *PermissionsUpdateOne) SetCanCreate(b bool) *PermissionsUpdateOne {
	puo.mutation.SetCanCreate(b)
	return puo
}

// SetNillableCanCreate sets the "can_create" field if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableCanCreate(b *bool) *PermissionsUpdateOne {
	if b != nil {
		puo.SetCanCreate(*b)
	}
	return puo
}

// SetCanEdit sets the "can_edit" field.
func (puo *PermissionsUpdateOne) SetCanEdit(b bool) *PermissionsUpdateOne {
	puo.mutation.SetCanEdit(b)
	return puo
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableCanEdit(b *bool) *PermissionsUpdateOne {
	if b != nil {
		puo.SetCanEdit(*b)
	}
	return puo
}

// SetCanDelete sets the "can_delete" field.
func (puo *PermissionsUpdateOne) SetCanDelete(b bool) *PermissionsUpdateOne {
	puo.mutation.SetCanDelete(b)
	return puo
}

// SetNillableCanDelete sets the "can_delete" field if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableCanDelete(b *bool) *PermissionsUpdateOne {
	if b != nil {
		puo.SetCanDelete(*b)
	}
	return puo
}

// SetCanExport sets the "can_export" field.
func (puo *PermissionsUpdateOne) SetCanExport(b bool) *PermissionsUpdateOne {
	puo.mutation.SetCanExport(b)
	return puo
}

// SetNillableCanExport sets the "can_export" field if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableCanExport(b *bool) *PermissionsUpdateOne {
	if b != nil {
		puo.SetCanExport(*b)
	}
	return puo
}

// SetCanPrint sets the "can_print" field.
func (puo *PermissionsUpdateOne) SetCanPrint(b bool) *PermissionsUpdateOne {
	puo.mutation.SetCanPrint(b)
	return puo
}

// SetNillableCanPrint sets the "can_print" field if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableCanPrint(b *bool) *PermissionsUpdateOne {
	if b != nil {
		puo.SetCanPrint(*b)
	}
	return puo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (puo *PermissionsUpdateOne) SetUserID(id int) *PermissionsUpdateOne {
	puo.mutation.SetUserID(id)
	return puo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (puo *PermissionsUpdateOne) SetNillableUserID(id *int) *PermissionsUpdateOne {
	if id != nil {
		puo = puo.SetUserID(*id)
	}
	return puo
}

// SetUser sets the "user" edge to the User entity.
func (puo *PermissionsUpdateOne) SetUser(u *User) *PermissionsUpdateOne {
	return puo.SetUserID(u.ID)
}

// Mutation returns the PermissionsMutation object of the builder.
func (puo *PermissionsUpdateOne) Mutation() *PermissionsMutation {
	return puo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (puo *PermissionsUpdateOne) ClearUser() *PermissionsUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// Where appends a list predicates to the PermissionsUpdate builder.
func (puo *PermissionsUpdateOne) Where(ps ...predicate.Permissions) *PermissionsUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PermissionsUpdateOne) Select(field string, fields ...string) *PermissionsUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Permissions entity.
func (puo *PermissionsUpdateOne) Save(ctx context.Context) (*Permissions, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PermissionsUpdateOne) SaveX(ctx context.Context) *Permissions {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PermissionsUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PermissionsUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PermissionsUpdateOne) sqlSave(ctx context.Context) (_node *Permissions, err error) {
	_spec := sqlgraph.NewUpdateSpec(permissions.Table, permissions.Columns, sqlgraph.NewFieldSpec(permissions.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Permissions.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permissions.FieldID)
		for _, f := range fields {
			if !permissions.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permissions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Module(); ok {
		_spec.SetField(permissions.FieldModule, field.TypeString, value)
	}
	if value, ok := puo.mutation.CanView(); ok {
		_spec.SetField(permissions.FieldCanView, field.TypeBool, value)
	}
	if value, ok := puo.mutation.CanCreate(); ok {
		_spec.SetField(permissions.FieldCanCreate, field.TypeBool, value)
	}
	if value, ok := puo.mutation.CanEdit(); ok {
		_spec.SetField(permissions.FieldCanEdit, field.TypeBool, value)
	}
	if value, ok := puo.mutation.CanDelete(); ok {
		_spec.SetField(permissions.FieldCanDelete, field.TypeBool, value)
	}
	if value, ok := puo.mutation.CanExport(); ok {
		_spec.SetField(permissions.FieldCanExport, field.TypeBool, value)
	}
	if value, ok := puo.mutation.CanPrint(); ok {
		_spec.SetField(permissions.FieldCanPrint, field.TypeBool, value)
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissions.UserTable,
			Columns: []string{permissions.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   permissions.UserTable,
			Columns: []string{permissions.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Permissions{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissions.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
