// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
	"github.com/Chaitu35/claimeasy/backend/ent/refreshtoken"
)

// RefreshTokenUpdate is the builder for updating RefreshToken entities.
type RefreshTokenUpdate struct {
	config
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtu *RefreshTokenUpdate) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdate {
	rtu.mutation.Where(ps...)
	return rtu
}

// SetToken sets the "token" field.
func (rtu *RefreshTokenUpdate) SetToken(s string) *RefreshTokenUpdate {
	rtu.mutation.SetToken(s)
	return rtu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableToken(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetToken(*s)
	}
	return rtu
}

// SetUserID sets the "user_id" field.
func (rtu *RefreshTokenUpdate) SetUserID(i int) *RefreshTokenUpdate {
	rtu.mutation.ResetUserID()
	rtu.mutation.SetUserID(i)
	return rtu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableUserID(i *int) *RefreshTokenUpdate {
	if i != nil {
		rtu.SetUserID(*i)
	}
	return rtu
}

// AddUserID adds i to the "user_id" field.
func (rtu *RefreshTokenUpdate) AddUserID(i int) *RefreshTokenUpdate {
	rtu.mutation.AddUserID(i)
	return rtu
}

// SetIssuedAt sets the "issued_at" field.
func (rtu *RefreshTokenUpdate) SetIssuedAt(t time.Time) *RefreshTokenUpdate {
	rtu.mutation.SetIssuedAt(t)
	return rtu
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableIssuedAt(t *time.Time) *RefreshTokenUpdate {
	if t != nil {
		rtu.SetIssuedAt(*t)
	}
	return rtu
}

// SetExpiresAt sets the "expires_at" field.
func (rtu *RefreshTokenUpdate) SetExpiresAt(t time.Time) *RefreshTokenUpdate {
	rtu.mutation.SetExpiresAt(t)
	return rtu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableExpiresAt(t *time.Time) *RefreshTokenUpdate {
	if t != nil {
		rtu.SetExpiresAt(*t)
	}
	return rtu
}

// SetIsRevoked sets the "is_revoked" field.
func (rtu *RefreshTokenUpdate) SetIsRevoked(b bool) *RefreshTokenUpdate {
	rtu.mutation.SetIsRevoked(b)
	return rtu
}

// SetNillableIsRevoked sets the "is_revoked" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableIsRevoked(b *bool) *RefreshTokenUpdate {
	if b != nil {
		rtu.SetIsRevoked(*b)
	}
	return rtu
}

// SetUserAgent sets the "user_agent" field.
func (rtu *RefreshTokenUpdate) SetUserAgent(s string) *RefreshTokenUpdate {
	rtu.mutation.SetUserAgent(s)
	return rtu
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableUserAgent(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetUserAgent(*s)
	}
	return rtu
}

// ClearUserAgent clears the value of the "user_agent" field.
func (rtu *RefreshTokenUpdate) ClearUserAgent() *RefreshTokenUpdate {
	rtu.mutation.ClearUserAgent()
	return rtu
}

// SetIPAddress sets the "ip_address" field.
func (rtu *RefreshTokenUpdate) SetIPAddress(s string) *RefreshTokenUpdate {
	rtu.mutation.SetIPAddress(s)
	return rtu
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableIPAddress(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetIPAddress(*s)
	}
	return rtu
}

// ClearIPAddress clears the value of the "ip_address" field.
func (rtu *RefreshTokenUpdate) ClearIPAddress() *RefreshTokenUpdate {
	rtu.mutation.ClearIPAddress()
	return rtu
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtu *RefreshTokenUpdate) Mutation() *RefreshTokenMutation {
	return rtu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rtu *RefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rtu.sqlSave, rtu.mutation, rtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := rtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rtu *RefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := rtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := rtu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rtu *RefreshTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeInt))
	if ps := rtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtu.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := rtu.mutation.UserID(); ok {
		_spec.SetField(refreshtoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := rtu.mutation.AddedUserID(); ok {
		_spec.AddField(refreshtoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := rtu.mutation.IssuedAt(); ok {
		_spec.SetField(refreshtoken.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := rtu.mutation.ExpiresAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := rtu.mutation.IsRevoked(); ok {
		_spec.SetField(refreshtoken.FieldIsRevoked, field.TypeBool, value)
	}
	if value, ok := rtu.mutation.UserAgent(); ok {
		_spec.SetField(refreshtoken.FieldUserAgent, field.TypeString, value)
	}
	if rtu.mutation.UserAgentCleared() {
		_spec.ClearField(refreshtoken.FieldUserAgent, field.TypeString)
	}
	if value, ok := rtu.mutation.IPAddress(); ok {
		_spec.SetField(refreshtoken.FieldIPAddress, field.TypeString, value)
	}
	if rtu.mutation.IPAddressCleared() {
		_spec.ClearField(refreshtoken.FieldIPAddress, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rtu.mutation.done = true
	return n, nil
}

// RefreshTokenUpdateOne is the builder for updating a single RefreshToken entity.
type RefreshTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// SetToken sets the "token" field.
func (rtuo *RefreshTokenUpdateOne) SetToken(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetToken(s)
	return rtuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableToken(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetToken(*s)
	}
	return rtuo
}

// SetUserID sets the "user_id" field.
func (rtuo *RefreshTokenUpdateOne) SetUserID(i int) *RefreshTokenUpdateOne {
	rtuo.mutation.ResetUserID()
	rtuo.mutation.SetUserID(i)
	return rtuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableUserID(i *int) *RefreshTokenUpdateOne {
	if i != nil {
		rtuo.SetUserID(*i)
	}
	return rtuo
}

// AddUserID adds i to the "user_id" field.
func (rtuo *RefreshTokenUpdateOne) AddUserID(i int) *RefreshTokenUpdateOne {
	rtuo.mutation.AddUserID(i)
	return rtuo
}

// SetIssuedAt sets the "issued_at" field.
func (rtuo *RefreshTokenUpdateOne) SetIssuedAt(t time.Time) *RefreshTokenUpdateOne {
	rtuo.mutation.SetIssuedAt(t)
	return rtuo
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableIssuedAt(t *time.Time) *RefreshTokenUpdateOne {
	if t != nil {
		rtuo.SetIssuedAt(*t)
	}
	return rtuo
}

// SetExpiresAt sets the "expires_at" field.
func (rtuo *RefreshTokenUpdateOne) SetExpiresAt(t time.Time) *RefreshTokenUpdateOne {
	rtuo.mutation.SetExpiresAt(t)
	return rtuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableExpiresAt(t *time.Time) *RefreshTokenUpdateOne {
	if t != nil {
		rtuo.SetExpiresAt(*t)
	}
	return rtuo
}

// SetIsRevoked sets the "is_revoked" field.
func (rtuo *RefreshTokenUpdateOne) SetIsRevoked(b bool) *RefreshTokenUpdateOne {
	rtuo.mutation.SetIsRevoked(b)
	return rtuo
}

// SetNillableIsRevoked sets the "is_revoked" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableIsRevoked(b *bool) *RefreshTokenUpdateOne {
	if b != nil {
		rtuo.SetIsRevoked(*b)
	}
	return rtuo
}

// SetUserAgent sets the "user_agent" field.
func (rtuo *RefreshTokenUpdateOne) SetUserAgent(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetUserAgent(s)
	return rtuo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableUserAgent(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetUserAgent(*s)
	}
	return rtuo
}

// ClearUserAgent clears the value of the "user_agent" field.
func (rtuo *RefreshTokenUpdateOne) ClearUserAgent() *RefreshTokenUpdateOne {
	rtuo.mutation.ClearUserAgent()
	return rtuo
}

// SetIPAddress sets the "ip_address" field.
func (rtuo *RefreshTokenUpdateOne) SetIPAddress(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetIPAddress(s)
	return rtuo
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableIPAddress(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetIPAddress(*s)
	}
	return rtuo
}

// ClearIPAddress clears the value of the "ip_address" field.
func (rtuo *RefreshTokenUpdateOne) ClearIPAddress() *RefreshTokenUpdateOne {
	rtuo.mutation.ClearIPAddress()
	return rtuo
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtuo *RefreshTokenUpdateOne) Mutation() *RefreshTokenMutation {
	return rtuo.mutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtuo *RefreshTokenUpdateOne) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdateOne {
	rtuo.mutation.Where(ps...)
	return rtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rtuo *RefreshTokenUpdateOne) Select(field string, fields ...string) *RefreshTokenUpdateOne {
	rtuo.fields = append([]string{field}, fields...)
	return rtuo
}

// Save executes the query and returns the updated RefreshToken entity.
func (rtuo *RefreshTokenUpdateOne) Save(ctx context.Context) (*RefreshToken, error) {
	return withHooks(ctx, rtuo.sqlSave, rtuo.mutation, rtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) SaveX(ctx context.Context) *RefreshToken {
	node, err := rtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rtuo *RefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := rtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := rtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rtuo *RefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *RefreshToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeInt))
	id, ok := rtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshtoken.FieldID)
		for _, f := range fields {
			if !refreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtuo.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := rtuo.mutation.UserID(); ok {
		_spec.SetField(refreshtoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := rtuo.mutation.AddedUserID(); ok {
		_spec.AddField(refreshtoken.FieldUserID, field.TypeInt, value)
	}
	if value, ok := rtuo.mutation.IssuedAt(); ok {
		_spec.SetField(refreshtoken.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := rtuo.mutation.ExpiresAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := rtuo.mutation.IsRevoked(); ok {
		_spec.SetField(refreshtoken.FieldIsRevoked, field.TypeBool, value)
	}
	if value, ok := rtuo.mutation.UserAgent(); ok {
		_spec.SetField(refreshtoken.FieldUserAgent, field.TypeString, value)
	}
	if rtuo.mutation.UserAgentCleared() {
		_spec.ClearField(refreshtoken.FieldUserAgent, field.TypeString)
	}
	if value, ok := rtuo.mutation.IPAddress(); ok {
		_spec.SetField(refreshtoken.FieldIPAddress, field.TypeString, value)
	}
	if rtuo.mutation.IPAddressCleared() {
		_spec.ClearField(refreshtoken.FieldIPAddress, field.TypeString)
	}
	_node = &RefreshToken{config: rtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rtuo.mutation.done = true
	return _node, nil
}
