// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Chaitu35/claimeasy/backend/ent/refreshtoken"
)

// RefreshTokenCreate is the builder for creating a RefreshToken entity.
type RefreshTokenCreate struct {
	config
	mutation *RefreshTokenMutation
	hooks    []Hook
}

// SetToken sets the "token" field.
func (rtc *RefreshTokenCreate) SetToken(s string) *RefreshTokenCreate {
	rtc.mutation.SetToken(s)
	return rtc
}

// SetUserID sets the "user_id" field.
func (rtc *RefreshTokenCreate) SetUserID(i int) *RefreshTokenCreate {
	rtc.mutation.SetUserID(i)
	return rtc
}

// SetIssuedAt sets the "issued_at" field.
func (rtc *RefreshTokenCreate) SetIssuedAt(t time.Time) *RefreshTokenCreate {
	rtc.mutation.SetIssuedAt(t)
	return rtc
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (rtc *RefreshTokenCreate) SetNillableIssuedAt(t *time.Time) *RefreshTokenCreate {
	if t != nil {
		rtc.SetIssuedAt(*t)
	}
	return rtc
}

// SetExpiresAt sets the "expires_at" field.
func (rtc *RefreshTokenCreate) SetExpiresAt(t time.Time) *RefreshTokenCreate {
	rtc.mutation.SetExpiresAt(t)
	return rtc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (rtc *RefreshTokenCreate) SetNillableExpiresAt(t *time.Time) *RefreshTokenCreate {
	if t != nil {
		rtc.SetExpiresAt(*t)
	}
	return rtc
}

// SetIsRevoked sets the "is_revoked" field.
func (rtc *RefreshTokenCreate) SetIsRevoked(b bool) *RefreshTokenCreate {
	rtc.mutation.SetIsRevoked(b)
	return rtc
}

// SetNillableIsRevoked sets the "is_revoked" field if the given value is not nil.
func (rtc *RefreshTokenCreate) SetNillableIsRevoked(b *bool) *RefreshTokenCreate {
	if b != nil {
		rtc.SetIsRevoked(*b)
	}
	return rtc
}

// SetUserAgent sets the "user_agent" field.
func (rtc *RefreshTokenCreate) SetUserAgent(s string) *RefreshTokenCreate {
	rtc.mutation.SetUserAgent(s)
	return rtc
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (rtc *RefreshTokenCreate) SetNillableUserAgent(s *string) *RefreshTokenCreate {
	if s != nil {
		rtc.SetUserAgent(*s)
	}
	return rtc
}

// SetIPAddress sets the "ip_address" field.
func (rtc *RefreshTokenCreate) SetIPAddress(s string) *RefreshTokenCreate {
	rtc.mutation.SetIPAddress(s)
	return rtc
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (rtc *RefreshTokenCreate) SetNillableIPAddress(s *string) *RefreshTokenCreate {
	if s != nil {
		rtc.SetIPAddress(*s)
	}
	return rtc
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtc *RefreshTokenCreate) Mutation() *RefreshTokenMutation {
	return rtc.mutation
}

// Save creates the RefreshToken in the database.
func (rtc *RefreshTokenCreate) Save(ctx context.Context) (*RefreshToken, error) {
	rtc.defaults()
	return withHooks(ctx, rtc.sqlSave, rtc.mutation, rtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rtc *RefreshTokenCreate) SaveX(ctx context.Context) *RefreshToken {
	v, err := rtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rtc *RefreshTokenCreate) Exec(ctx context.Context) error {
	_, err := rtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtc *RefreshTokenCreate) ExecX(ctx context.Context) {
	if err := rtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rtc *RefreshTokenCreate) defaults() {
	if _, ok := rtc.mutation.IssuedAt(); !ok {
		v := refreshtoken.DefaultIssuedAt()
		rtc.mutation.SetIssuedAt(v)
	}
	if _, ok := rtc.mutation.ExpiresAt(); !ok {
		v := refreshtoken.DefaultExpiresAt()
		rtc.mutation.SetExpiresAt(v)
	}
	if _, ok := rtc.mutation.IsRevoked(); !ok {
		v := refreshtoken.DefaultIsRevoked
		rtc.mutation.SetIsRevoked(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtc *RefreshTokenCreate) check() error {
	if _, ok := rtc.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "RefreshToken.token"`)}
	}
	if _, ok := rtc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RefreshToken.user_id"`)}
	}
	if _, ok := rtc.mutation.IssuedAt(); !ok {
		return &ValidationError{Name: "issued_at", err: errors.New(`ent: missing required field "RefreshToken.issued_at"`)}
	}
	if _, ok := rtc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "RefreshToken.expires_at"`)}
	}
	if _, ok := rtc.mutation.IsRevoked(); !ok {
		return &ValidationError{Name: "is_revoked", err: errors.New(`ent: missing required field "RefreshToken.is_revoked"`)}
	}
	return nil
}

func (rtc *RefreshTokenCreate) sqlSave(ctx context.Context) (*RefreshToken, error) {
	if err := rtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rtc.mutation.id = &_node.ID
	rtc.mutation.done = true
	return _node, nil
}

func (rtc *RefreshTokenCreate) createSpec() (*RefreshToken, *sqlgraph.CreateSpec) {
	var (
		_node = &RefreshToken{config: rtc.config}
		_spec = sqlgraph.NewCreateSpec(refreshtoken.Table, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeInt))
	)
	if value, ok := rtc.mutation.Token(); ok {
		_spec.SetField(refreshtoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := rtc.mutation.UserID(); ok {
		_spec.SetField(refreshtoken.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := rtc.mutation.IssuedAt(); ok {
		_spec.SetField(refreshtoken.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = value
	}
	if value, ok := rtc.mutation.ExpiresAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := rtc.mutation.IsRevoked(); ok {
		_spec.SetField(refreshtoken.FieldIsRevoked, field.TypeBool, value)
		_node.IsRevoked = value
	}
	if value, ok := rtc.mutation.UserAgent(); ok {
		_spec.SetField(refreshtoken.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := rtc.mutation.IPAddress(); ok {
		_spec.SetField(refreshtoken.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = &value
	}
	return _node, _spec
}

// RefreshTokenCreateBulk is the builder for creating many RefreshToken entities in bulk.
type RefreshTokenCreateBulk struct {
	config
	err      error
	builders []*RefreshTokenCreate
}

// Save creates the RefreshToken entities in the database.
func (rtcb *RefreshTokenCreateBulk) Save(ctx context.Context) ([]*RefreshToken, error) {
	if rtcb.err != nil {
		return nil, rtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rtcb.builders))
	nodes := make([]*RefreshToken, len(rtcb.builders))
	mutators := make([]Mutator, len(rtcb.builders))
	for i := range rtcb.builders {
		func(i int, root context.Context) {
			builder := rtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RefreshTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rtcb *RefreshTokenCreateBulk) SaveX(ctx context.Context) []*RefreshToken {
	v, err := rtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rtcb *RefreshTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := rtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtcb *RefreshTokenCreateBulk) ExecX(ctx context.Context) {
	if err := rtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
