// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Chaitu35/claimeasy/backend/ent/cliniccreds"
	"github.com/Chaitu35/claimeasy/backend/ent/clinics"
	"github.com/Chaitu35/claimeasy/backend/ent/doctors"
	"github.com/Chaitu35/claimeasy/backend/ent/passwordresettoken"
	"github.com/Chaitu35/claimeasy/backend/ent/permissions"
	"github.com/Chaitu35/claimeasy/backend/ent/refreshtoken"
	"github.com/Chaitu35/claimeasy/backend/ent/schema"
	"github.com/Chaitu35/claimeasy/backend/ent/user"
	"github.com/Chaitu35/claimeasy/backend/pkg/core/role"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cliniccredsFields := schema.ClinicCreds{}.Fields()
	_ = cliniccredsFields
	// cliniccredsDescSystem is the schema descriptor for system field.
	cliniccredsDescSystem := cliniccredsFields[0].Descriptor()
	// cliniccreds.SystemValidator is a validator for the "system" field. It is called by the builders before save.
	cliniccreds.SystemValidator = cliniccredsDescSystem.Validators[0].(func(string) error)
	// cliniccredsDescUsername is the schema descriptor for username field.
	cliniccredsDescUsername := cliniccredsFields[1].Descriptor()
	// cliniccreds.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	cliniccreds.UsernameValidator = cliniccredsDescUsername.Validators[0].(func(string) error)
	// cliniccredsDescPassword is the schema descriptor for password field.
	cliniccredsDescPassword := cliniccredsFields[2].Descriptor()
	// cliniccreds.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	cliniccreds.PasswordValidator = cliniccredsDescPassword.Validators[0].(func(string) error)
	clinicsFields := schema.Clinics{}.Fields()
	_ = clinicsFields
	// clinicsDescName is the schema descriptor for name field.
	clinicsDescName := clinicsFields[0].Descriptor()
	// clinics.NameValidator is a validator for the "name" field. It is called by the builders before save.
	clinics.NameValidator = clinicsDescName.Validators[0].(func(string) error)
	// clinicsDescCity is the schema descriptor for city field.
	clinicsDescCity := clinicsFields[1].Descriptor()
	// clinics.CityValidator is a validator for the "city" field. It is called by the builders before save.
	clinics.CityValidator = clinicsDescCity.Validators[0].(func(string) error)
	// clinicsDescRegulatory is the schema descriptor for regulatory field.
	clinicsDescRegulatory := clinicsFields[2].Descriptor()
	// clinics.RegulatoryValidator is a validator for the "regulatory" field. It is called by the builders before save.
	clinics.RegulatoryValidator = clinicsDescRegulatory.Validators[0].(func(string) error)
	doctorsFields := schema.Doctors{}.Fields()
	_ = doctorsFields
	// doctorsDescName is the schema descriptor for name field.
	doctorsDescName := doctorsFields[0].Descriptor()
	// doctors.NameValidator is a validator for the "name" field. It is called by the builders before save.
	doctors.NameValidator = doctorsDescName.Validators[0].(func(string) error)
	// doctorsDescSpecialization is the schema descriptor for specialization field.
	doctorsDescSpecialization := doctorsFields[1].Descriptor()
	// doctors.SpecializationValidator is a validator for the "specialization" field. It is called by the builders before save.
	doctors.SpecializationValidator = doctorsDescSpecialization.Validators[0].(func(string) error)
	// doctorsDescLicense is the schema descriptor for license field.
	doctorsDescLicense := doctorsFields[2].Descriptor()
	// doctors.LicenseValidator is a validator for the "license" field. It is called by the builders before save.
	doctors.LicenseValidator = doctorsDescLicense.Validators[0].(func(string) error)
	passwordresettokenFields := schema.PasswordResetToken{}.Fields()
	_ = passwordresettokenFields
	// passwordresettokenDescToken is the schema descriptor for token field.
	passwordresettokenDescToken := passwordresettokenFields[0].Descriptor()
	// passwordresettoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	passwordresettoken.TokenValidator = func() func(string) error {
		validators := passwordresettokenDescToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token string) error {
			for _, fn := range fns {
				if err := fn(token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// passwordresettokenDescCreatedAt is the schema descriptor for created_at field.
	passwordresettokenDescCreatedAt := passwordresettokenFields[2].Descriptor()
	// passwordresettoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordresettoken.DefaultCreatedAt = passwordresettokenDescCreatedAt.Default.(func() time.Time)
	permissionsFields := schema.Permissions{}.Fields()
	_ = permissionsFields
	// permissionsDescCanView is the schema descriptor for can_view field.
	permissionsDescCanView := permissionsFields[1].Descriptor()
	// permissions.DefaultCanView holds the default value on creation for the can_view field.
	permissions.DefaultCanView = permissionsDescCanView.Default.(bool)
	// permissionsDescCanCreate is the schema descriptor for can_create field.
	permissionsDescCanCreate := permissionsFields[2].Descriptor()
	// permissions.DefaultCanCreate holds the default value on creation for the can_create field.
	permissions.DefaultCanCreate = permissionsDescCanCreate.Default.(bool)
	// permissionsDescCanEdit is the schema descriptor for can_edit field.
	permissionsDescCanEdit := permissionsFields[3].Descriptor()
	// permissions.DefaultCanEdit holds the default value on creation for the can_edit field.
	permissions.DefaultCanEdit = permissionsDescCanEdit.Default.(bool)
	// permissionsDescCanDelete is the schema descriptor for can_delete field.
	permissionsDescCanDelete := permissionsFields[4].Descriptor()
	// permissions.DefaultCanDelete holds the default value on creation for the can_delete field.
	permissions.DefaultCanDelete = permissionsDescCanDelete.Default.(bool)
	// permissionsDescCanExport is the schema descriptor for can_export field.
	permissionsDescCanExport := permissionsFields[5].Descriptor()
	// permissions.DefaultCanExport holds the default value on creation for the can_export field.
	permissions.DefaultCanExport = permissionsDescCanExport.Default.(bool)
	// permissionsDescCanPrint is the schema descriptor for can_print field.
	permissionsDescCanPrint := permissionsFields[6].Descriptor()
	// permissions.DefaultCanPrint holds the default value on creation for the can_print field.
	permissions.DefaultCanPrint = permissionsDescCanPrint.Default.(bool)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescIssuedAt is the schema descriptor for issued_at field.
	refreshtokenDescIssuedAt := refreshtokenFields[2].Descriptor()
	// refreshtoken.DefaultIssuedAt holds the default value on creation for the issued_at field.
	refreshtoken.DefaultIssuedAt = refreshtokenDescIssuedAt.Default.(func() time.Time)
	// refreshtokenDescExpiresAt is the schema descriptor for expires_at field.
	refreshtokenDescExpiresAt := refreshtokenFields[3].Descriptor()
	// refreshtoken.DefaultExpiresAt holds the default value on creation for the expires_at field.
	refreshtoken.DefaultExpiresAt = refreshtokenDescExpiresAt.Default.(func() time.Time)
	// refreshtokenDescIsRevoked is the schema descriptor for is_revoked field.
	refreshtokenDescIsRevoked := refreshtokenFields[4].Descriptor()
	// refreshtoken.DefaultIsRevoked holds the default value on creation for the is_revoked field.
	refreshtoken.DefaultIsRevoked = refreshtokenDescIsRevoked.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescMobile is the schema descriptor for mobile field.
	userDescMobile := userFields[4].Descriptor()
	// user.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	user.MobileValidator = userDescMobile.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[5].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = role.Role(userDescRole.Default.(string))
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[6].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[9].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[11].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
