// Code generated by ent, DO NOT EDIT.

package clinics

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the clinics type in the database.
	Label = "clinics"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldRegulatory holds the string denoting the regulatory field in the database.
	FieldRegulatory = "regulatory"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldFacilityID holds the string denoting the facilityid field in the database.
	FieldFacilityID = "facility_id"
	// EdgeClinicCreds holds the string denoting the clinic_creds edge name in mutations.
	EdgeClinicCreds = "clinic_creds"
	// EdgeDoctors holds the string denoting the doctors edge name in mutations.
	EdgeDoctors = "doctors"
	// Table holds the table name of the clinics in the database.
	Table = "clinics"
	// ClinicCredsTable is the table that holds the clinic_creds relation/edge.
	ClinicCredsTable = "clinic_creds"
	// ClinicCredsInverseTable is the table name for the ClinicCreds entity.
	// It exists in this package in order to avoid circular dependency with the "cliniccreds" package.
	ClinicCredsInverseTable = "clinic_creds"
	// ClinicCredsColumn is the table column denoting the clinic_creds relation/edge.
	ClinicCredsColumn = "clinics_clinic_creds"
	// DoctorsTable is the table that holds the doctors relation/edge.
	DoctorsTable = "doctors"
	// DoctorsInverseTable is the table name for the Doctors entity.
	// It exists in this package in order to avoid circular dependency with the "doctors" package.
	DoctorsInverseTable = "doctors"
	// DoctorsColumn is the table column denoting the doctors relation/edge.
	DoctorsColumn = "clinics_doctors"
)

// Columns holds all SQL columns for clinics fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCity,
	FieldRegulatory,
	FieldEmail,
	FieldPhone,
	FieldFacilityID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CityValidator is a validator for the "city" field. It is called by the builders before save.
	CityValidator func(string) error
	// RegulatoryValidator is a validator for the "regulatory" field. It is called by the builders before save.
	RegulatoryValidator func(string) error
)

// OrderOption defines the ordering options for the Clinics queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByRegulatory orders the results by the regulatory field.
func ByRegulatory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegulatory, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByFacilityID orders the results by the facilityID field.
func ByFacilityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFacilityID, opts...).ToFunc()
}

// ByClinicCredsCount orders the results by clinic_creds count.
func ByClinicCredsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClinicCredsStep(), opts...)
	}
}

// ByClinicCreds orders the results by clinic_creds terms.
func ByClinicCreds(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClinicCredsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDoctorsCount orders the results by doctors count.
func ByDoctorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDoctorsStep(), opts...)
	}
}

// ByDoctors orders the results by doctors terms.
func ByDoctors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDoctorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newClinicCredsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClinicCredsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ClinicCredsTable, ClinicCredsColumn),
	)
}
func newDoctorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DoctorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DoctorsTable, DoctorsColumn),
	)
}
