// Code generated by ent, DO NOT EDIT.

package clinics

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
	regulatory "github.com/Chaitu35/claimeasy/backend/pkg/core"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Clinics {
	return predicate.Clinics(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Clinics {
	return predicate.Clinics(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Clinics {
	return predicate.Clinics(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Clinics {
	return predicate.Clinics(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Clinics {
	return predicate.Clinics(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Clinics {
	return predicate.Clinics(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Clinics {
	return predicate.Clinics(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldName, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldCity, v))
}

// Regulatory applies equality check predicate on the "regulatory" field. It's identical to RegulatoryEQ.
func Regulatory(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldEQ(FieldRegulatory, vc))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldEmail, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldPhone, v))
}

// FacilityID applies equality check predicate on the "facilityID" field. It's identical to FacilityIDEQ.
func FacilityID(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldFacilityID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContainsFold(FieldName, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasSuffix(FieldCity, v))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContainsFold(FieldCity, v))
}

// RegulatoryEQ applies the EQ predicate on the "regulatory" field.
func RegulatoryEQ(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldEQ(FieldRegulatory, vc))
}

// RegulatoryNEQ applies the NEQ predicate on the "regulatory" field.
func RegulatoryNEQ(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldNEQ(FieldRegulatory, vc))
}

// RegulatoryIn applies the In predicate on the "regulatory" field.
func RegulatoryIn(vs ...regulatory.Regulatory) predicate.Clinics {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Clinics(sql.FieldIn(FieldRegulatory, v...))
}

// RegulatoryNotIn applies the NotIn predicate on the "regulatory" field.
func RegulatoryNotIn(vs ...regulatory.Regulatory) predicate.Clinics {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Clinics(sql.FieldNotIn(FieldRegulatory, v...))
}

// RegulatoryGT applies the GT predicate on the "regulatory" field.
func RegulatoryGT(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldGT(FieldRegulatory, vc))
}

// RegulatoryGTE applies the GTE predicate on the "regulatory" field.
func RegulatoryGTE(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldGTE(FieldRegulatory, vc))
}

// RegulatoryLT applies the LT predicate on the "regulatory" field.
func RegulatoryLT(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldLT(FieldRegulatory, vc))
}

// RegulatoryLTE applies the LTE predicate on the "regulatory" field.
func RegulatoryLTE(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldLTE(FieldRegulatory, vc))
}

// RegulatoryContains applies the Contains predicate on the "regulatory" field.
func RegulatoryContains(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldContains(FieldRegulatory, vc))
}

// RegulatoryHasPrefix applies the HasPrefix predicate on the "regulatory" field.
func RegulatoryHasPrefix(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldHasPrefix(FieldRegulatory, vc))
}

// RegulatoryHasSuffix applies the HasSuffix predicate on the "regulatory" field.
func RegulatoryHasSuffix(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldHasSuffix(FieldRegulatory, vc))
}

// RegulatoryEqualFold applies the EqualFold predicate on the "regulatory" field.
func RegulatoryEqualFold(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldEqualFold(FieldRegulatory, vc))
}

// RegulatoryContainsFold applies the ContainsFold predicate on the "regulatory" field.
func RegulatoryContainsFold(v regulatory.Regulatory) predicate.Clinics {
	vc := string(v)
	return predicate.Clinics(sql.FieldContainsFold(FieldRegulatory, vc))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.Clinics {
	return predicate.Clinics(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.Clinics {
	return predicate.Clinics(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContainsFold(FieldEmail, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.Clinics {
	return predicate.Clinics(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.Clinics {
	return predicate.Clinics(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContainsFold(FieldPhone, v))
}

// FacilityIDEQ applies the EQ predicate on the "facilityID" field.
func FacilityIDEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEQ(FieldFacilityID, v))
}

// FacilityIDNEQ applies the NEQ predicate on the "facilityID" field.
func FacilityIDNEQ(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNEQ(FieldFacilityID, v))
}

// FacilityIDIn applies the In predicate on the "facilityID" field.
func FacilityIDIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldIn(FieldFacilityID, vs...))
}

// FacilityIDNotIn applies the NotIn predicate on the "facilityID" field.
func FacilityIDNotIn(vs ...string) predicate.Clinics {
	return predicate.Clinics(sql.FieldNotIn(FieldFacilityID, vs...))
}

// FacilityIDGT applies the GT predicate on the "facilityID" field.
func FacilityIDGT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGT(FieldFacilityID, v))
}

// FacilityIDGTE applies the GTE predicate on the "facilityID" field.
func FacilityIDGTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldGTE(FieldFacilityID, v))
}

// FacilityIDLT applies the LT predicate on the "facilityID" field.
func FacilityIDLT(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLT(FieldFacilityID, v))
}

// FacilityIDLTE applies the LTE predicate on the "facilityID" field.
func FacilityIDLTE(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldLTE(FieldFacilityID, v))
}

// FacilityIDContains applies the Contains predicate on the "facilityID" field.
func FacilityIDContains(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContains(FieldFacilityID, v))
}

// FacilityIDHasPrefix applies the HasPrefix predicate on the "facilityID" field.
func FacilityIDHasPrefix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasPrefix(FieldFacilityID, v))
}

// FacilityIDHasSuffix applies the HasSuffix predicate on the "facilityID" field.
func FacilityIDHasSuffix(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldHasSuffix(FieldFacilityID, v))
}

// FacilityIDEqualFold applies the EqualFold predicate on the "facilityID" field.
func FacilityIDEqualFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldEqualFold(FieldFacilityID, v))
}

// FacilityIDContainsFold applies the ContainsFold predicate on the "facilityID" field.
func FacilityIDContainsFold(v string) predicate.Clinics {
	return predicate.Clinics(sql.FieldContainsFold(FieldFacilityID, v))
}

// HasClinicCreds applies the HasEdge predicate on the "clinic_creds" edge.
func HasClinicCreds() predicate.Clinics {
	return predicate.Clinics(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ClinicCredsTable, ClinicCredsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClinicCredsWith applies the HasEdge predicate on the "clinic_creds" edge with a given conditions (other predicates).
func HasClinicCredsWith(preds ...predicate.ClinicCreds) predicate.Clinics {
	return predicate.Clinics(func(s *sql.Selector) {
		step := newClinicCredsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDoctors applies the HasEdge predicate on the "doctors" edge.
func HasDoctors() predicate.Clinics {
	return predicate.Clinics(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DoctorsTable, DoctorsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoctorsWith applies the HasEdge predicate on the "doctors" edge with a given conditions (other predicates).
func HasDoctorsWith(preds ...predicate.Doctors) predicate.Clinics {
	return predicate.Clinics(func(s *sql.Selector) {
		step := newDoctorsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Clinics) predicate.Clinics {
	return predicate.Clinics(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Clinics) predicate.Clinics {
	return predicate.Clinics(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Clinics) predicate.Clinics {
	return predicate.Clinics(sql.NotPredicates(p))
}
