// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClinicCredsColumns holds the columns for the "clinic_creds" table.
	ClinicCredsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "system", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "clinics_clinic_creds", Type: field.TypeInt},
	}
	// ClinicCredsTable holds the schema information for the "clinic_creds" table.
	ClinicCredsTable = &schema.Table{
		Name:       "clinic_creds",
		Columns:    ClinicCredsColumns,
		PrimaryKey: []*schema.Column{ClinicCredsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "clinic_creds_clinics_clinic_creds",
				Columns:    []*schema.Column{ClinicCredsColumns[4]},
				RefColumns: []*schema.Column{ClinicsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ClinicsColumns holds the columns for the "clinics" table.
	ClinicsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "city", Type: field.TypeString},
		{Name: "regulatory", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "facility_id", Type: field.TypeString, Unique: true},
	}
	// ClinicsTable holds the schema information for the "clinics" table.
	ClinicsTable = &schema.Table{
		Name:       "clinics",
		Columns:    ClinicsColumns,
		PrimaryKey: []*schema.Column{ClinicsColumns[0]},
	}
	// DoctorsColumns holds the columns for the "doctors" table.
	DoctorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "specialization", Type: field.TypeString},
		{Name: "license", Type: field.TypeString, Unique: true},
		{Name: "clinics_doctors", Type: field.TypeInt},
	}
	// DoctorsTable holds the schema information for the "doctors" table.
	DoctorsTable = &schema.Table{
		Name:       "doctors",
		Columns:    DoctorsColumns,
		PrimaryKey: []*schema.Column{DoctorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "doctors_clinics_doctors",
				Columns:    []*schema.Column{DoctorsColumns[4]},
				RefColumns: []*schema.Column{ClinicsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PasswordResetTokensColumns holds the columns for the "password_reset_tokens" table.
	PasswordResetTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PasswordResetTokensTable holds the schema information for the "password_reset_tokens" table.
	PasswordResetTokensTable = &schema.Table{
		Name:       "password_reset_tokens",
		Columns:    PasswordResetTokensColumns,
		PrimaryKey: []*schema.Column{PasswordResetTokensColumns[0]},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "module", Type: field.TypeString},
		{Name: "can_view", Type: field.TypeBool, Default: false},
		{Name: "can_create", Type: field.TypeBool, Default: false},
		{Name: "can_edit", Type: field.TypeBool, Default: false},
		{Name: "can_delete", Type: field.TypeBool, Default: false},
		{Name: "can_export", Type: field.TypeBool, Default: false},
		{Name: "can_print", Type: field.TypeBool, Default: false},
		{Name: "user_permissions", Type: field.TypeInt, Nullable: true},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "permissions_users_permissions",
				Columns:    []*schema.Column{PermissionsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "issued_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "is_revoked", Type: field.TypeBool, Default: false},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "mobile", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeString, Default: "coder"},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "national_id", Type: field.TypeString, Nullable: true},
		{Name: "country", Type: field.TypeString, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserPasswordResetTokensColumns holds the columns for the "user_password_reset_tokens" table.
	UserPasswordResetTokensColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "password_reset_token_id", Type: field.TypeInt},
	}
	// UserPasswordResetTokensTable holds the schema information for the "user_password_reset_tokens" table.
	UserPasswordResetTokensTable = &schema.Table{
		Name:       "user_password_reset_tokens",
		Columns:    UserPasswordResetTokensColumns,
		PrimaryKey: []*schema.Column{UserPasswordResetTokensColumns[0], UserPasswordResetTokensColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_password_reset_tokens_user_id",
				Columns:    []*schema.Column{UserPasswordResetTokensColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_password_reset_tokens_password_reset_token_id",
				Columns:    []*schema.Column{UserPasswordResetTokensColumns[1]},
				RefColumns: []*schema.Column{PasswordResetTokensColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClinicCredsTable,
		ClinicsTable,
		DoctorsTable,
		PasswordResetTokensTable,
		PermissionsTable,
		RefreshTokensTable,
		UsersTable,
		UserPasswordResetTokensTable,
	}
)

func init() {
	ClinicCredsTable.ForeignKeys[0].RefTable = ClinicsTable
	DoctorsTable.ForeignKeys[0].RefTable = ClinicsTable
	PermissionsTable.ForeignKeys[0].RefTable = UsersTable
	UserPasswordResetTokensTable.ForeignKeys[0].RefTable = UsersTable
	UserPasswordResetTokensTable.ForeignKeys[1].RefTable = PasswordResetTokensTable
}
