// Code generated by ent, DO NOT EDIT.

package permissions

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the permissions type in the database.
	Label = "permissions"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModule holds the string denoting the module field in the database.
	FieldModule = "module"
	// FieldCanView holds the string denoting the can_view field in the database.
	FieldCanView = "can_view"
	// FieldCanCreate holds the string denoting the can_create field in the database.
	FieldCanCreate = "can_create"
	// FieldCanEdit holds the string denoting the can_edit field in the database.
	FieldCanEdit = "can_edit"
	// FieldCanDelete holds the string denoting the can_delete field in the database.
	FieldCanDelete = "can_delete"
	// FieldCanExport holds the string denoting the can_export field in the database.
	FieldCanExport = "can_export"
	// FieldCanPrint holds the string denoting the can_print field in the database.
	FieldCanPrint = "can_print"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the permissions in the database.
	Table = "permissions"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "permissions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_permissions"
)

// Columns holds all SQL columns for permissions fields.
var Columns = []string{
	FieldID,
	FieldModule,
	FieldCanView,
	FieldCanCreate,
	FieldCanEdit,
	FieldCanDelete,
	FieldCanExport,
	FieldCanPrint,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "permissions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_permissions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCanView holds the default value on creation for the "can_view" field.
	DefaultCanView bool
	// DefaultCanCreate holds the default value on creation for the "can_create" field.
	DefaultCanCreate bool
	// DefaultCanEdit holds the default value on creation for the "can_edit" field.
	DefaultCanEdit bool
	// DefaultCanDelete holds the default value on creation for the "can_delete" field.
	DefaultCanDelete bool
	// DefaultCanExport holds the default value on creation for the "can_export" field.
	DefaultCanExport bool
	// DefaultCanPrint holds the default value on creation for the "can_print" field.
	DefaultCanPrint bool
)

// OrderOption defines the ordering options for the Permissions queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModule orders the results by the module field.
func ByModule(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModule, opts...).ToFunc()
}

// ByCanView orders the results by the can_view field.
func ByCanView(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanView, opts...).ToFunc()
}

// ByCanCreate orders the results by the can_create field.
func ByCanCreate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanCreate, opts...).ToFunc()
}

// ByCanEdit orders the results by the can_edit field.
func ByCanEdit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanEdit, opts...).ToFunc()
}

// ByCanDelete orders the results by the can_delete field.
func ByCanDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanDelete, opts...).ToFunc()
}

// ByCanExport orders the results by the can_export field.
func ByCanExport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanExport, opts...).ToFunc()
}

// ByCanPrint orders the results by the can_print field.
func ByCanPrint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanPrint, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
