// Code generated by ent, DO NOT EDIT.

package permissions

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Permissions {
	return predicate.Permissions(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Permissions {
	return predicate.Permissions(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Permissions {
	return predicate.Permissions(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Permissions {
	return predicate.Permissions(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Permissions {
	return predicate.Permissions(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Permissions {
	return predicate.Permissions(sql.FieldLTE(FieldID, id))
}

// Module applies equality check predicate on the "module" field. It's identical to ModuleEQ.
func Module(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldModule, v))
}

// CanView applies equality check predicate on the "can_view" field. It's identical to CanViewEQ.
func CanView(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanView, v))
}

// CanCreate applies equality check predicate on the "can_create" field. It's identical to CanCreateEQ.
func CanCreate(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanCreate, v))
}

// CanEdit applies equality check predicate on the "can_edit" field. It's identical to CanEditEQ.
func CanEdit(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanEdit, v))
}

// CanDelete applies equality check predicate on the "can_delete" field. It's identical to CanDeleteEQ.
func CanDelete(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanDelete, v))
}

// CanExport applies equality check predicate on the "can_export" field. It's identical to CanExportEQ.
func CanExport(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanExport, v))
}

// CanPrint applies equality check predicate on the "can_print" field. It's identical to CanPrintEQ.
func CanPrint(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanPrint, v))
}

// ModuleEQ applies the EQ predicate on the "module" field.
func ModuleEQ(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldModule, v))
}

// ModuleNEQ applies the NEQ predicate on the "module" field.
func ModuleNEQ(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldModule, v))
}

// ModuleIn applies the In predicate on the "module" field.
func ModuleIn(vs ...string) predicate.Permissions {
	return predicate.Permissions(sql.FieldIn(FieldModule, vs...))
}

// ModuleNotIn applies the NotIn predicate on the "module" field.
func ModuleNotIn(vs ...string) predicate.Permissions {
	return predicate.Permissions(sql.FieldNotIn(FieldModule, vs...))
}

// ModuleGT applies the GT predicate on the "module" field.
func ModuleGT(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldGT(FieldModule, v))
}

// ModuleGTE applies the GTE predicate on the "module" field.
func ModuleGTE(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldGTE(FieldModule, v))
}

// ModuleLT applies the LT predicate on the "module" field.
func ModuleLT(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldLT(FieldModule, v))
}

// ModuleLTE applies the LTE predicate on the "module" field.
func ModuleLTE(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldLTE(FieldModule, v))
}

// ModuleContains applies the Contains predicate on the "module" field.
func ModuleContains(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldContains(FieldModule, v))
}

// ModuleHasPrefix applies the HasPrefix predicate on the "module" field.
func ModuleHasPrefix(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldHasPrefix(FieldModule, v))
}

// ModuleHasSuffix applies the HasSuffix predicate on the "module" field.
func ModuleHasSuffix(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldHasSuffix(FieldModule, v))
}

// ModuleEqualFold applies the EqualFold predicate on the "module" field.
func ModuleEqualFold(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldEqualFold(FieldModule, v))
}

// ModuleContainsFold applies the ContainsFold predicate on the "module" field.
func ModuleContainsFold(v string) predicate.Permissions {
	return predicate.Permissions(sql.FieldContainsFold(FieldModule, v))
}

// CanViewEQ applies the EQ predicate on the "can_view" field.
func CanViewEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanView, v))
}

// CanViewNEQ applies the NEQ predicate on the "can_view" field.
func CanViewNEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldCanView, v))
}

// CanCreateEQ applies the EQ predicate on the "can_create" field.
func CanCreateEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanCreate, v))
}

// CanCreateNEQ applies the NEQ predicate on the "can_create" field.
func CanCreateNEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldCanCreate, v))
}

// CanEditEQ applies the EQ predicate on the "can_edit" field.
func CanEditEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanEdit, v))
}

// CanEditNEQ applies the NEQ predicate on the "can_edit" field.
func CanEditNEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldCanEdit, v))
}

// CanDeleteEQ applies the EQ predicate on the "can_delete" field.
func CanDeleteEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanDelete, v))
}

// CanDeleteNEQ applies the NEQ predicate on the "can_delete" field.
func CanDeleteNEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldCanDelete, v))
}

// CanExportEQ applies the EQ predicate on the "can_export" field.
func CanExportEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanExport, v))
}

// CanExportNEQ applies the NEQ predicate on the "can_export" field.
func CanExportNEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldCanExport, v))
}

// CanPrintEQ applies the EQ predicate on the "can_print" field.
func CanPrintEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldEQ(FieldCanPrint, v))
}

// CanPrintNEQ applies the NEQ predicate on the "can_print" field.
func CanPrintNEQ(v bool) predicate.Permissions {
	return predicate.Permissions(sql.FieldNEQ(FieldCanPrint, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Permissions {
	return predicate.Permissions(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Permissions {
	return predicate.Permissions(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Permissions) predicate.Permissions {
	return predicate.Permissions(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Permissions) predicate.Permissions {
	return predicate.Permissions(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Permissions) predicate.Permissions {
	return predicate.Permissions(sql.NotPredicates(p))
}
