// Code generated by ent, DO NOT EDIT.

package doctors

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the doctors type in the database.
	Label = "doctors"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSpecialization holds the string denoting the specialization field in the database.
	FieldSpecialization = "specialization"
	// FieldLicense holds the string denoting the license field in the database.
	FieldLicense = "license"
	// EdgeClinics holds the string denoting the clinics edge name in mutations.
	EdgeClinics = "clinics"
	// Table holds the table name of the doctors in the database.
	Table = "doctors"
	// ClinicsTable is the table that holds the clinics relation/edge.
	ClinicsTable = "doctors"
	// ClinicsInverseTable is the table name for the Clinics entity.
	// It exists in this package in order to avoid circular dependency with the "clinics" package.
	ClinicsInverseTable = "clinics"
	// ClinicsColumn is the table column denoting the clinics relation/edge.
	ClinicsColumn = "clinics_doctors"
)

// Columns holds all SQL columns for doctors fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSpecialization,
	FieldLicense,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "doctors"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"clinics_doctors",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SpecializationValidator is a validator for the "specialization" field. It is called by the builders before save.
	SpecializationValidator func(string) error
	// LicenseValidator is a validator for the "license" field. It is called by the builders before save.
	LicenseValidator func(string) error
)

// OrderOption defines the ordering options for the Doctors queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySpecialization orders the results by the specialization field.
func BySpecialization(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecialization, opts...).ToFunc()
}

// ByLicense orders the results by the license field.
func ByLicense(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicense, opts...).ToFunc()
}

// ByClinicsField orders the results by clinics field.
func ByClinicsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClinicsStep(), sql.OrderByField(field, opts...))
	}
}
func newClinicsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClinicsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClinicsTable, ClinicsColumn),
	)
}
