// Code generated by ent, DO NOT EDIT.

package doctors

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Chaitu35/claimeasy/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Doctors {
	return predicate.Doctors(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Doctors {
	return predicate.Doctors(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Doctors {
	return predicate.Doctors(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Doctors {
	return predicate.Doctors(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Doctors {
	return predicate.Doctors(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Doctors {
	return predicate.Doctors(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Doctors {
	return predicate.Doctors(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldName, v))
}

// Specialization applies equality check predicate on the "specialization" field. It's identical to SpecializationEQ.
func Specialization(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldSpecialization, v))
}

// License applies equality check predicate on the "license" field. It's identical to LicenseEQ.
func License(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldLicense, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Doctors {
	return predicate.Doctors(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Doctors {
	return predicate.Doctors(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldContainsFold(FieldName, v))
}

// SpecializationEQ applies the EQ predicate on the "specialization" field.
func SpecializationEQ(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldSpecialization, v))
}

// SpecializationNEQ applies the NEQ predicate on the "specialization" field.
func SpecializationNEQ(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldNEQ(FieldSpecialization, v))
}

// SpecializationIn applies the In predicate on the "specialization" field.
func SpecializationIn(vs ...string) predicate.Doctors {
	return predicate.Doctors(sql.FieldIn(FieldSpecialization, vs...))
}

// SpecializationNotIn applies the NotIn predicate on the "specialization" field.
func SpecializationNotIn(vs ...string) predicate.Doctors {
	return predicate.Doctors(sql.FieldNotIn(FieldSpecialization, vs...))
}

// SpecializationGT applies the GT predicate on the "specialization" field.
func SpecializationGT(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldGT(FieldSpecialization, v))
}

// SpecializationGTE applies the GTE predicate on the "specialization" field.
func SpecializationGTE(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldGTE(FieldSpecialization, v))
}

// SpecializationLT applies the LT predicate on the "specialization" field.
func SpecializationLT(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldLT(FieldSpecialization, v))
}

// SpecializationLTE applies the LTE predicate on the "specialization" field.
func SpecializationLTE(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldLTE(FieldSpecialization, v))
}

// SpecializationContains applies the Contains predicate on the "specialization" field.
func SpecializationContains(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldContains(FieldSpecialization, v))
}

// SpecializationHasPrefix applies the HasPrefix predicate on the "specialization" field.
func SpecializationHasPrefix(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldHasPrefix(FieldSpecialization, v))
}

// SpecializationHasSuffix applies the HasSuffix predicate on the "specialization" field.
func SpecializationHasSuffix(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldHasSuffix(FieldSpecialization, v))
}

// SpecializationEqualFold applies the EqualFold predicate on the "specialization" field.
func SpecializationEqualFold(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEqualFold(FieldSpecialization, v))
}

// SpecializationContainsFold applies the ContainsFold predicate on the "specialization" field.
func SpecializationContainsFold(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldContainsFold(FieldSpecialization, v))
}

// LicenseEQ applies the EQ predicate on the "license" field.
func LicenseEQ(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEQ(FieldLicense, v))
}

// LicenseNEQ applies the NEQ predicate on the "license" field.
func LicenseNEQ(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldNEQ(FieldLicense, v))
}

// LicenseIn applies the In predicate on the "license" field.
func LicenseIn(vs ...string) predicate.Doctors {
	return predicate.Doctors(sql.FieldIn(FieldLicense, vs...))
}

// LicenseNotIn applies the NotIn predicate on the "license" field.
func LicenseNotIn(vs ...string) predicate.Doctors {
	return predicate.Doctors(sql.FieldNotIn(FieldLicense, vs...))
}

// LicenseGT applies the GT predicate on the "license" field.
func LicenseGT(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldGT(FieldLicense, v))
}

// LicenseGTE applies the GTE predicate on the "license" field.
func LicenseGTE(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldGTE(FieldLicense, v))
}

// LicenseLT applies the LT predicate on the "license" field.
func LicenseLT(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldLT(FieldLicense, v))
}

// LicenseLTE applies the LTE predicate on the "license" field.
func LicenseLTE(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldLTE(FieldLicense, v))
}

// LicenseContains applies the Contains predicate on the "license" field.
func LicenseContains(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldContains(FieldLicense, v))
}

// LicenseHasPrefix applies the HasPrefix predicate on the "license" field.
func LicenseHasPrefix(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldHasPrefix(FieldLicense, v))
}

// LicenseHasSuffix applies the HasSuffix predicate on the "license" field.
func LicenseHasSuffix(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldHasSuffix(FieldLicense, v))
}

// LicenseEqualFold applies the EqualFold predicate on the "license" field.
func LicenseEqualFold(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldEqualFold(FieldLicense, v))
}

// LicenseContainsFold applies the ContainsFold predicate on the "license" field.
func LicenseContainsFold(v string) predicate.Doctors {
	return predicate.Doctors(sql.FieldContainsFold(FieldLicense, v))
}

// HasClinics applies the HasEdge predicate on the "clinics" edge.
func HasClinics() predicate.Doctors {
	return predicate.Doctors(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClinicsTable, ClinicsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClinicsWith applies the HasEdge predicate on the "clinics" edge with a given conditions (other predicates).
func HasClinicsWith(preds ...predicate.Clinics) predicate.Doctors {
	return predicate.Doctors(func(s *sql.Selector) {
		step := newClinicsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Doctors) predicate.Doctors {
	return predicate.Doctors(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Doctors) predicate.Doctors {
	return predicate.Doctors(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Doctors) predicate.Doctors {
	return predicate.Doctors(sql.NotPredicates(p))
}
